from __future__ import annotations

from l5r_auto.clans import CraneClan
from l5r_auto.keywords import (
    Air,
    Artisan,
    Courtier,
    Cursed,
    Daimyo,
    Duelist,
    Expendable,
    Experienced,
    IronCrane,
    Jester,
    Loyal,
    Magistrate,
    Poet,
    Reserve,
    Samurai,
    Shugenja,
    SoulOf,
    Unique,
)
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition

from ..common import Personality

Asahina_Hirakane = Personality(
    card_id=12091,
    title="Asahina Hirakane",
    force=2,
    chi=3,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=4,
    clan=[CraneClan],
    keywords=[Air, Shugenja, SoulOf("Asahina Minori")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Daidoji_Hiroteru = Personality(
    card_id=12092,
    title="Daidoji Hiroteru",
    force=2,
    chi=2,
    personal_honor=2,
    gold_cost=5,
    honor_requirement=6,
    clan=[CraneClan],
    keywords=[IronCrane, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Daidoji_Taenaru = Personality(
    card_id=12093,
    title="Daidoji Taenaru",
    force=3,
    chi=3,
    personal_honor=2,
    gold_cost=8,
    honor_requirement=2,
    clan=[CraneClan],
    keywords=[Samurai, SoulOf("Daidoji Tae")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Doji_Masachika = Personality(
    card_id=12094,
    title="Doji Masachika",
    force=2,
    chi=3,
    personal_honor=2,
    gold_cost=4,
    honor_requirement=7,
    clan=[CraneClan],
    keywords=[Expendable, Magistrate, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Doji_Norime = Personality(
    card_id=12095,
    title="Doji Norime",
    force=2,
    chi=2,
    personal_honor=3,
    gold_cost=5,
    honor_requirement=4,
    clan=[CraneClan],
    keywords=[Magistrate, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Doji_Senkiku = Personality(
    card_id=12096,
    title="Doji Senkiku",
    force=3,
    chi=4,
    personal_honor=2,
    gold_cost=7,
    honor_requirement=6,
    clan=[CraneClan],
    keywords=[Magistrate, Samurai, SoulOf("Doji Hitomaro")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Doji_Tashihime = Personality(
    card_id=12097,
    title="Doji Tashihime",
    force=0,
    chi=3,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=8,
    clan=[CraneClan],
    keywords=[Artisan, Poet, SoulOf("Doji Nukada")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Kakita_Akitomo = Personality(
    card_id=12098,
    title="Kakita Akitomo",
    force=0,
    chi=4,
    personal_honor=2,
    gold_cost=5,
    honor_requirement=6,
    clan=[CraneClan],
    keywords=[Artisan, Courtier, Jester],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Kakita_Hikai = Personality(
    card_id=12099,
    title="Kakita Hikai",
    force=0,
    chi=2,
    personal_honor=1,
    gold_cost=4,
    honor_requirement=4,
    clan=[CraneClan],
    keywords=[Expendable, Artisan, Courtier, Jester],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Kakita_Ikura = Personality(
    card_id=12100,
    title="Kakita Ikura",
    force=1,
    chi=5,
    personal_honor=3,
    gold_cost=9,
    honor_requirement=8,
    clan=[CraneClan],
    keywords=[Loyal, Unique, Artisan, Courtier, Cursed, Daimyo],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Kakita_Mitsumichi = Personality(
    card_id=12101,
    title="Kakita Mitsumichi",
    force=1,
    chi=4,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=5,
    clan=[CraneClan],
    keywords=[Duelist, Samurai, SoulOf("Kakita Yariga")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Kakita_Ujirou_Experienced = Personality(
    card_id=12102,
    title="Kakita Ujirou",
    force=4,
    chi=4,
    personal_honor=3,
    gold_cost=11,
    honor_requirement=4,
    clan=[CraneClan],
    keywords=[Duelist, Reserve, Unique, Experienced("1"), Magistrate, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
