from __future__ import annotations
from ..common import Personality
from l5r_auto.clans import NagaFaction, UnicornClan
from l5r_auto.keywords import BattleMaiden, Cavalry, ClanChampion, Commander, DeathPriest, Doomseeker, Experienced, Kami, Loyal, Naga, Paragon, Samurai, Shugenja, SoulOf, Tactician, Unique, Water, WhiteGuard
from l5r_auto.legality import CelestialEdition, EmperorEdition, ModernEdition
'<b>Open:</b> Target a Personality without attachments: He may not be assigned, and will not move, to battlefields.'
Iuchi_Shunshi = Personality(card_id=4002, title='Iuchi Shunshi', force=4, chi=3, personal_honor=3, gold_cost=11, honor_requirement=3, clan=[UnicornClan], keywords=[Unique, Doomseeker, Shugenja, SoulOf('Iuchi Karasu Experienced 2')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"Naleesh's unit straightens during each player's Straighten Phase.<br><b>Battle:</b> Target an enemy unit: Naleesh overruns it. Bow it. Destroy all cards in it without attachments and without Cavalry."
Moto_Naleesh = Personality(card_id=5354, title='Moto Naleesh', force=6, chi=5, personal_honor=4, gold_cost=13, honor_requirement=10, clan=[UnicornClan, NagaFaction], keywords=[Cavalry, Loyal, Tactician, Unique, ClanChampion, Commander, Kami, Naga, Paragon, Samurai], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
Moto_Rani = Personality(card_id=5360, title='Moto Rani', force=3, chi=3, personal_honor=1, gold_cost=6, honor_requirement=None, clan=[UnicornClan], keywords=[Cavalry, DeathPriest, Shugenja, Water], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"Shigeru has +1F while she has an Item.<br><b>Reaction:</b> After a Limited action targets your Personality, negate the action's effects. Permanently reduce Shigeru's Personal Honor by the number of other Personalities you control. If her Personal Honor is now 0, she commits seppuku."
Moto_Shigeru = Personality(card_id=5370, title='Moto Shigeru', force=3, chi=3, personal_honor=2, gold_cost=8, honor_requirement=None, clan=[UnicornClan], keywords=[Cavalry, Samurai, SoulOf('Moto Gurban')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"Shunsuke has a Force bonus equal to the highest number of dead Personalities in any one discard pile. <br><b>Limited:</b> Target another player's discarded Personality. He becomes honorably dead."
Moto_Shunsuke = Personality(card_id=5371, title='Moto Shunsuke', force=3, chi=4, personal_honor=0, gold_cost=8, honor_requirement=None, clan=[UnicornClan], keywords=[Cavalry, DeathPriest, Shugenja, SoulOf('Moto Akikazu')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
Moto_Taha = Personality(card_id=5379, title='Moto Taha', force=1, chi=3, personal_honor=2, gold_cost=6, honor_requirement=3, clan=[UnicornClan], keywords=[Cavalry, Tactician, Samurai, SoulOf('Moto Munoru')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> If you control any Cavalry units at the current battlefield, move Tetsuo there. After this moves him, Ranged 4 Attack.'
Moto_Tetsuo = Personality(card_id=5382, title='Moto Tetsuo', force=4, chi=2, personal_honor=2, gold_cost=8, honor_requirement=2, clan=[UnicornClan], keywords=[Samurai, SoulOf('Moto Shanyu'), WhiteGuard], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
Shinjo_Baeshuko = Personality(card_id=6863, title='Shinjo Baeshuko', force=3, chi=2, personal_honor=2, gold_cost=5, honor_requirement=6, clan=[UnicornClan], keywords=[Cavalry, Samurai, SoulOf('Shinjo Huang')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> Ranged 4 Attack.'
Shinjo_EunSahng = Personality(card_id=6872, title='Shinjo Eun-Sahng', force=5, chi=4, personal_honor=3, gold_cost=10, honor_requirement=4, clan=[UnicornClan], keywords=[Tactician, Samurai, SoulOf('Shinjo Chu-Yeung')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> If Horibe is opposed, target a Personality: Bow or straighten him.'
Shinjo_Horibe = Personality(card_id=6885, title='Shinjo Horibe', force=4, chi=3, personal_honor=2, gold_cost=8, honor_requirement=0, clan=[UnicornClan], keywords=[Cavalry, Commander, Samurai, SoulOf('Shinjo Hwarang')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Reaction:</b> After Itao enters play, target a Follower in your hand: Attach it to Itao, paying all costs.'
Shinjo_Itao = Personality(card_id=6895, title='Shinjo Itao', force=3, chi=3, personal_honor=3, gold_cost=7, honor_requirement=0, clan=[UnicornClan], keywords=[Cavalry, Samurai, SoulOf('Shinjo Goshi')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Reaction:</b> After your target Personality enters play: Create a 1F <b>Cavalry </b> Follower and attach it to him.'
Shinjo_KiChang_Experienced = Personality(card_id=6905, title='Shinjo Ki-Chang', force=4, chi=4, personal_honor=3, gold_cost=10, honor_requirement=0, clan=[UnicornClan], keywords=[Cavalry, Tactician, Unique, Commander, Experienced('1'), Samurai], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
Shinjo_Taeken = Personality(card_id=6950, title='Shinjo Taeken', force=3, chi=3, personal_honor=2, gold_cost=6, honor_requirement=3, clan=[UnicornClan], keywords=[Cavalry, Commander, Samurai, SoulOf('Shinjo Tae-hyun')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Reaction:</b> After engaging at Ryoko's battlefield, target a Personality or Follower opposing her: Give it a Force penalty equal to Ryoko's Personal Honor."
Utaku_Ryoko = Personality(card_id=9094, title='Utaku Ryoko', force=4, chi=2, personal_honor=3, gold_cost=8, honor_requirement=4, clan=[UnicornClan], keywords=[Cavalry, BattleMaiden, Paragon, Samurai, SoulOf('Utaku Liu-Xeung')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
Utaku_Tsukiko = Personality(card_id=9107, title='Utaku Tsukiko', force=3, chi=2, personal_honor=4, gold_cost=7, honor_requirement=5, clan=[UnicornClan], keywords=[Cavalry, BattleMaiden, Paragon, Samurai, SoulOf('Utaku Fusae')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])