from __future__ import annotations

from l5r_auto.clans import UnicornClan
from l5r_auto.keywords import (
    BattleMaiden,
    Cavalry,
    Chieftain,
    Commander,
    Conqueror,
    Experienced,
    Imperial,
    Loyal,
    Magistrate,
    Samurai,
    Scout,
    Shugenja,
    SoulOf,
    Tactician,
    Unique,
    Water,
)
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition

from ..common import Personality

Iuchi_Daitoru = Personality(
    id=12181,
    title="Iuchi Daitoru",
    force=1,
    chi=4,
    personal_honor=3,
    gold_cost=5,
    honor_requirement=None,
    clan=[UnicornClan],
    keywords=[Magistrate, Shugenja, Water],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Moto_Aikenro = Personality(
    id=12182,
    title="Moto Aikenro",
    force=3,
    chi=2,
    personal_honor=1,
    gold_cost=6,
    honor_requirement=3,
    clan=[UnicornClan],
    keywords=[Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Moto_Taigo_Shogun_Experienced_2 = Personality(
    id=12183,
    title="Moto Taigo, Shogun",
    force=4,
    chi=4,
    personal_honor=2,
    gold_cost=12,
    honor_requirement=None,
    clan=[UnicornClan],
    keywords=[
        Cavalry,
        Conqueror,
        Experienced("2"),
        Tactician,
        Unique,
        Commander,
        Imperial,
        Samurai,
    ],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Moto_Yaotsu = Personality(
    id=12184,
    title="Moto Yao-tsu",
    force=4,
    chi=3,
    personal_honor=2,
    gold_cost=9,
    honor_requirement=None,
    clan=[UnicornClan],
    keywords=[Cavalry, Commander, Samurai, SoulOf("Moto Qu Yuan")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Moto_Zaitsuta = Personality(
    id=12185,
    title="Moto Zaitsuta",
    force=5,
    chi=3,
    personal_honor=2,
    gold_cost=10,
    honor_requirement=None,
    clan=[UnicornClan],
    keywords=[Cavalry, Chieftain, Samurai, SoulOf("Moto Zhijuan")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Shinjo_Hamura = Personality(
    id=12186,
    title="Shinjo Hamura",
    force=3,
    chi=3,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=3,
    clan=[UnicornClan],
    keywords=[Magistrate, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Shinjo_Jalendu = Personality(
    id=12187,
    title="Shinjo Jalendu",
    force=4,
    chi=2,
    personal_honor=2,
    gold_cost=8,
    honor_requirement=4,
    clan=[UnicornClan],
    keywords=[Cavalry, Samurai, Scout, SoulOf("Shinjo Jalair")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Shinjo_Jaoshen = Personality(
    id=12188,
    title="Shinjo Jao-shen",
    force=0,
    chi=2,
    personal_honor=2,
    gold_cost=3,
    honor_requirement=4,
    clan=[UnicornClan],
    keywords=[Cavalry, Loyal, Magistrate, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Shinjo_Nobunaga = Personality(
    id=12189,
    title="Shinjo Nobunaga",
    force=3,
    chi=3,
    personal_honor=1,
    gold_cost=8,
    honor_requirement=None,
    clan=[UnicornClan],
    keywords=[Cavalry, SoulOf("Shinjo Xushen")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Shinjo_Taehyun_Experienced = Personality(
    id=12190,
    title="Shinjo Tae-hyun",
    force=3,
    chi=3,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=8,
    clan=[UnicornClan],
    keywords=[Cavalry, Unique, Experienced("1"), Magistrate, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Shinjo_Zhitae = Personality(
    id=12191,
    title="Shinjo Zhi-tae",
    force=4,
    chi=3,
    personal_honor=2,
    gold_cost=8,
    honor_requirement=4,
    clan=[UnicornClan],
    keywords=[Cavalry, Commander, Samurai, SoulOf("Shinjo Ji-tae")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Utaku_Kazue = Personality(
    id=12192,
    title="Utaku Kazue",
    force=3,
    chi=2,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=5,
    clan=[UnicornClan],
    keywords=[Cavalry, BattleMaiden, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
