from __future__ import annotations
from .common import Spell
from l5r_auto.keywords import Air, Earth, Experienced, Fire, Maho, Thunder, Unique, Void, Water
from l5r_auto.legality import CelestialEdition, EmperorEdition, ModernEdition
'While this Shugenja is Water, he contributes Force to his army even if bowed.<br><b>Water Limited:</b> Once per game, create a +2F/+0C <b>Water &#149; Weapon</b> Item with the ability, "<b>Battle:</b> Bow a target enemy card without attachments" and attach it to one of your Personalities.'
Bo_of_Water = Spell(card_id=1084, title='Bo of Water', gold_cost=2, focus_value=3, keywords=[Water], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Bow this Shugenja unless he is Void: Look at the top three cards of your Fate or Dynasty deck. You may put one or two of these cards on the bottom of your deck. Put the remaining cards on the top of your deck in any order.'
Control_Your_Destiny = Spell(card_id=1489, title='Control Your Destiny', gold_cost=0, focus_value=2, keywords=[Void], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle/Open:</b> Destroy this card and target your dead Personality: Bring him into play at this Shugenja's location, paying all costs. Permanently give him <b>Shadowlands </b>and<b> Undead</b>. Lose 2 Honor."
Essence_of_Undeath = Spell(card_id=2380, title='Essence of Undeath', gold_cost=2, focus_value=3, keywords=[Maho], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Even if this unit is not at the current battlefield, if any enemy units are there, target your Personality: Move him there. Straighten him if he moved. If he is an Ancestor and this Shugenja is Water, you may take an additional Battle action.'
Intervening_Spirit = Spell(card_id=3788, title='Intervening Spirit', gold_cost=0, focus_value=3, keywords=[Water], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Once per game: Create a +3F/+1C <b>Fire &#149; Weapon</b> Item with the ability, "<b>Battle:</b> Bow this card unless this Personality is Fire, and target an enemy card without attachments: Destroy it" and attach it to one of your Personalities.'
Katana_of_Fire_Experienced = Spell(card_id=4291, title='Katana of Fire', gold_cost=4, focus_value=2, keywords=[Experienced('1'), Fire], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> Once per game, after this card enters play, target your Spell and pay Gold equal to its base Gold Cost: This card permanently copies the Spell's keywords, traits, and its base abilities that do not themselves copy abilities."
Mastering_the_Elements = Spell(card_id=4874, title='Mastering the Elements', gold_cost=0, focus_value=4, keywords=[Unique], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Even if this unit is not at the current battlefield, bow this Shugenja and your performing Spirit, and target an enemy card without attachments and with Force lower than or equal to your Spirit's: Destroy the enemy card. If this Shugenja is Earth, gain 1 Honor."
Rage_of_the_Spirits = Spell(card_id=6141, title='Rage of the Spirits', gold_cost=0, focus_value=2, keywords=[Earth], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Reaction:</b> After the resolution of a Battle action, if this card is in your hand, choose your performing Thunder Shugenja: Attach this card to him.<br><b>Reaction:</b> After the resolution of a Battle action, if this Shugenja is at the current battlefield, target a Personality who performed it: Bow him.'
Stormless_Fury = Spell(card_id=7512, title='Stormless Fury', gold_cost=0, focus_value=2, keywords=[Thunder], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'This Shugenja has +6F.<br><b>Battle:</b> Even if this card is bowed, if this Shugenja is Water: Straighten him. You may move him home.<br><b>Battle:</b> Bow this card and target an enemy Personality: Move him home. If he moved, negate his <i>(future)</i> movement.'
Strength_of_the_Tsunami = Spell(card_id=7562, title='Strength of the Tsunami', gold_cost=8, focus_value=2, keywords=[Water], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> After another player's action targets your defending Personality, if this Shugenja is Earth, destroy this card: Negate the Personality's destruction from the action's effects.<br><b>Battle/Open:</b> Even if this unit is not at the current battlefield, bow this Shugenja and target your Nonhuman: Straighten it."
Taming_the_Beast = Spell(card_id=7767, title='Taming the Beast', gold_cost=0, focus_value=1, keywords=[Earth], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'After you gain Honor from destroying an army in battle resolution, if this Shugenja is Earth and in the winning army: Gain 2 Honor.<br><b>Battle:</b> If you are the Defender, target a Personality: Move him to the current battlefield. Straighten his unit if he moved.'
The_Earth_Flows = Spell(card_id=8038, title='The Earth Flows', gold_cost=0, focus_value=2, keywords=[Earth], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Limited:</b> Bow this Shugenja and target another player's Personality: If he is dishonorable, Kolat, Ninja, or Shadowlands, his controller loses Honor equal to his base Personal Honor. If this Shugenja is Air, gain 1 Honor."
Winds_of_Dismissal = Spell(card_id=9344, title='Winds of Dismissal', gold_cost=2, focus_value=2, keywords=[Air], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])