from __future__ import annotations
from ..common import Personality
from l5r_auto.clans import BrotherhoodOfShinsei, NinjaFaction, ShadowlandsFaction, SpiderClan
from l5r_auto.keywords import AmbassadorToTheEmpire, Artisan, Bloodspeaker, Commander, Conqueror, Courtier, DarkFistOfIron, Experienced, FaceOfGhosts, Immortal, Kensai, Khadi, Loyal, MasterSensei, Monk, Ninja, Paragon, Samurai, Shadowlands, Shugenja, Undead, Unique, Vicious, WorkerOfFlesh
from l5r_auto.legality import CelestialEdition, EmperorEdition, ModernEdition
"After Kiuchi enters play, lose 1 Honor.<br><b>Open:</b> Target your performing Personality and your performing Nonhuman or Undead Personality to set each Personality's Force equal to the higher printed Force of the two."
Chuda_Kiuchi = Personality(card_id=1356, title='Chuda Kiuchi', force=2, chi=4, personal_honor=0, gold_cost=7, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Artisan, Shadowlands, Shugenja, Vicious, WorkerOfFlesh], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'After Bukaro enters play: Lose 1 Honor.<br><b>Limited:</b> Pay 2 Gold and target a Personality: Create a 1F Follower and attach it to the Personality.'
Daigotsu_Bukaro = Personality(card_id=1707, title='Daigotsu Bukaro', force=4, chi=3, personal_honor=0, gold_cost=7, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Conqueror, Commander, Samurai, Shadowlands], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'After Miki enters play: Lose 1 Honor. <br>After your Events Phase: You may remove a Dark Virtue in your hand or discard pile from the game. If you did not remove one, destroy Miki.'
Daigotsu_Miki = Personality(card_id=1747, title='Daigotsu Miki', force=8, chi=2, personal_honor=1, gold_cost=8, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Conqueror, DarkFistOfIron, Paragon, Samurai, Shadowlands, Undead], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'After Yajinden enters play: Lose 4 Honor.<br><b>Limited:</b> Target a dead Personality: Yajinden raises him from the dead. Bring him into play <i>(under your control)</i> ignoring costs and Honor Requirements. Remove him from the game when the turn ends.'
Daigotsu_Yajinden_Experienced_3 = Personality(card_id=1783, title='Daigotsu Yajinden', force=6, chi=6, personal_honor=0, gold_cost=12, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Experienced('3'), Loyal, Unique, Artisan, Bloodspeaker, Khadi, Shadowlands, Shugenja], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"After Sawaki enters play: Lose 2 Honor.<br><b>Reaction:</b> After another player's Battle action targets Sawaki, destroy him: Create two 1F/1C/0PH <b>Spider Clan &#149; Shadowlands &#149; Ninja</b> Personalities at the current battlefield."
Goju_Sawaki = Personality(card_id=2858, title='Goju Sawaki', force=2, chi=2, personal_honor=0, gold_cost=5, honor_requirement=None, clan=[SpiderClan, NinjaFaction, ShadowlandsFaction], keywords=[Immortal, Ninja, Shadowlands], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Target an enemy Personality with lower Force or without attached Weapons: Omigawa knocks him aside. Move the targeted card home. Bow him if he moved and Omigawa has a Weapon.'
Omigawa = Personality(card_id=5695, title='Omigawa', force=5, chi=2, personal_honor=0, gold_cost=8, honor_requirement=None, clan=[SpiderClan, BrotherhoodOfShinsei], keywords=[Kensai, FaceOfGhosts, MasterSensei, Monk], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"Other players' maximum hand sizes are reduced by 1.<br><b>Reaction:</b> After another player's Political action targets one of your Personalities: Negate its effects."
Taishuu_Experienced = Personality(card_id=7733, title='Taishuu', force=4, chi=4, personal_honor=0, gold_cost=9, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Experienced('Mirumoto Taishuu'), Loyal, Unique, AmbassadorToTheEmpire, Courtier, Paragon, Samurai, Shadowlands], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])