from __future__ import annotations
from ..common import Personality
from l5r_auto.clans import BrotherhoodOfShinsei, NinjaFaction, ShadowlandsFaction, SpiderClan
from l5r_auto.keywords import AdvisorToTheEmeraldChampion, BogHag, Commander, Conqueror, DarkScionOfFire, DragonChild, Experienced, Infiltrator, Kensai, Loyal, Magistrate, Monk, Naval, Ninja, Nonhuman, ObsidianChampion, Paragon, Samurai, Shadowlands, SilkFever, TigersClaw, Undead, Unique
from l5r_auto.legality import CelestialEdition, EmperorEdition, ModernEdition
"After the first time each phase another player's action targets Bofana: If the action was not performed by a card with <i>(current)</i> Force equal to or higher than Bofana's base Force, the player discards a card."
Daigotsu_Bofana = Personality(card_id=1706, title='Daigotsu Bofana', force=7, chi=4, personal_honor=0, gold_cost=10, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Loyal, DarkScionOfFire, Paragon, Samurai, Shadowlands], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'Enters play paying 2 less Gold if you are a Lion Clan player.<br>After Hotako enters play: Lose 2 Honor.<br><b>Fear Open:</b> Target a Personality: He may not perform actions this turn.'
Daigotsu_Hotako_Experienced_3 = Personality(card_id=1726, title='Daigotsu Hotako', force=7, chi=4, personal_honor=0, gold_cost=11, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Experienced('3'), Naval, Unique, ObsidianChampion, Paragon, Samurai, Shadowlands], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'After Shikenuro enters play: Lose 2 Honor.'
Daigotsu_Shikenuro = Personality(card_id=1765, title='Daigotsu Shikenuro', force=5, chi=2, personal_honor=0, gold_cost=7, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Conqueror, Commander, Samurai, Shadowlands, SilkFever, Undead], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Open:</b> Remove a target Personality in any player's discard pile from the game: Fukuzo wears his skin. Until the next time this game this ability is used, Fukuzo copies one keyword, and one ability that does not itself copy abilities, from the Personality."
Fukuzo_Experienced = Personality(card_id=2728, title='Fukuzo', force=5, chi=2, personal_honor=0, gold_cost=7, honor_requirement=None, clan=[SpiderClan, ShadowlandsFaction], keywords=[Experienced('Chuda Fukuzo'), Unique, AdvisorToTheEmeraldChampion, BogHag, Infiltrator, Magistrate, Nonhuman, Samurai, Shadowlands], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"After Yurishi enters play: Lose 3 Honor.<br><b>Reaction:</b> After another player's Battle action targets Yurishi: He disappears into the shadows. Move him home. If he is no longer a legal target for the action, negate its effects on him."
Goju_Yurishi = Personality(card_id=2862, title='Goju Yurishi', force=4, chi=3, personal_honor=0, gold_cost=7, honor_requirement=None, clan=[SpiderClan, NinjaFaction, ShadowlandsFaction], keywords=[DragonChild, Ninja, Shadowlands], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Bow Sutigu or one of his Weapons, and target an enemy card: Negate its straightening <i>(until the turn ends)</i> if it is an attachment. Bow it.'
Sutigu = Personality(card_id=7676, title='Sutigu', force=3, chi=3, personal_honor=1, gold_cost=6, honor_requirement=None, clan=[SpiderClan, BrotherhoodOfShinsei], keywords=[Kensai, Monk, TigersClaw], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])