from __future__ import annotations
from dataclasses import dataclass
from l5r_auto.card import Ability, Trait
from l5r_auto.cards.personalities.common import Personality
from l5r_auto.clans import BrotherhoodOfShinsei, NinjaFaction, ShadowlandsFaction, SpiderClan
from l5r_auto.keywords import BogHag, Commander, Daimyo, DragonChild, Duelist, Expendable, Experienced, Goblin, Infiltrator, Monk, Ninja, Nonhuman, Reserve, Samurai, Shadowlands, Shugenja, Unique
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition
Daigotsu_Atsushi_Experienced = Personality(id=12161, title='Daigotsu Atsushi', force=4, chi=4, honor_requirement=None, personal_honor=0, gold_cost=10, clan=[SpiderClan], keywords=[Duelist, Unique, Experienced('1'), Samurai], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Daigotsu_Hachiko = Personality(id=12162, title='Daigotsu Hachiko', force=3, chi=4, honor_requirement=None, personal_honor=0, gold_cost=5, clan=[SpiderClan], keywords=[Duelist, Reserve, Samurai], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Daigotsu_Hayigi = Personality(id=12163, title='Daigotsu Hayigi', force=3, chi=4, honor_requirement=None, personal_honor=0, gold_cost=7, clan=[SpiderClan, ShadowlandsFaction], keywords=[BogHag, Infiltrator, Nonhuman, Shadowlands, Shugenja], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Daigotsu_Shaoru = Personality(id=12164, title='Daigotsu Shaoru', force=3, chi=3, honor_requirement=None, personal_honor=0, gold_cost=5, clan=[SpiderClan], keywords=[Duelist, Samurai], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Goju_Kumoru = Personality(id=12165, title='Goju Kumoru', force=3, chi=3, honor_requirement=None, personal_honor=0, gold_cost=6, clan=[SpiderClan, NinjaFaction, ShadowlandsFaction], keywords=[Ninja, Shadowlands], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Goju_Mitsuru = Personality(id=12166, title='Goju Mitsuru', force=2, chi=2, honor_requirement=None, personal_honor=0, gold_cost=4, clan=[SpiderClan, NinjaFaction, ShadowlandsFaction], keywords=[Reserve, Ninja, Shadowlands], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Goju_Yurishi_Experienced_2 = Personality(id=12167, title='Goju Yurishi', force=4, chi=4, honor_requirement=None, personal_honor=0, gold_cost=9, clan=[SpiderClan, NinjaFaction, ShadowlandsFaction], keywords=[Experienced('2'), Unique, Daimyo, DragonChild, Ninja, Shadowlands], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Kokujin_Gunjao = Personality(id=12168, title='Kokujin Gunjao', force=2, chi=2, honor_requirement=None, personal_honor=0, gold_cost=4, clan=[SpiderClan, BrotherhoodOfShinsei, ShadowlandsFaction], keywords=[Duelist, Monk, Shadowlands], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Naibu = Personality(id=12169, title='Naibu', force=3, chi=3, honor_requirement=None, personal_honor=0, gold_cost=4, clan=[SpiderClan, ShadowlandsFaction], keywords=[Expendable, Commander, Goblin, Nonhuman, Shadowlands], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
The_Twisted_One = Personality(id=12170, title='The Twisted One', force=3, chi=3, honor_requirement=None, personal_honor=0, gold_cost=5, clan=[SpiderClan, NinjaFaction, ShadowlandsFaction], keywords=[Ninja, Shadowlands], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])