from __future__ import annotations

from l5r_auto.clans import (
    BrotherhoodOfShinsei,
    NinjaFaction,
    ShadowlandsFaction,
    SpiderClan,
)
from l5r_auto.keywords import (
    BogHag,
    Commander,
    Daimyo,
    DragonChild,
    Duelist,
    Expendable,
    Experienced,
    Goblin,
    Infiltrator,
    Monk,
    Ninja,
    Nonhuman,
    Reserve,
    Samurai,
    Shadowlands,
    Shugenja,
    Unique,
)
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition

from ..common import Personality

Daigotsu_Atsushi_Experienced = Personality(
    id=12161,
    title="Daigotsu Atsushi",
    force=4,
    chi=4,
    personal_honor=0,
    gold_cost=10,
    honor_requirement=None,
    clan=[SpiderClan],
    keywords=[Duelist, Unique, Experienced("1"), Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Daigotsu_Hachiko = Personality(
    id=12162,
    title="Daigotsu Hachiko",
    force=3,
    chi=4,
    personal_honor=0,
    gold_cost=5,
    honor_requirement=None,
    clan=[SpiderClan],
    keywords=[Duelist, Reserve, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Daigotsu_Hayigi = Personality(
    id=12163,
    title="Daigotsu Hayigi",
    force=3,
    chi=4,
    personal_honor=0,
    gold_cost=7,
    honor_requirement=None,
    clan=[SpiderClan, ShadowlandsFaction],
    keywords=[BogHag, Infiltrator, Nonhuman, Shadowlands, Shugenja],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Daigotsu_Shaoru = Personality(
    id=12164,
    title="Daigotsu Shaoru",
    force=3,
    chi=3,
    personal_honor=0,
    gold_cost=5,
    honor_requirement=None,
    clan=[SpiderClan],
    keywords=[Duelist, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Goju_Kumoru = Personality(
    id=12165,
    title="Goju Kumoru",
    force=3,
    chi=3,
    personal_honor=0,
    gold_cost=6,
    honor_requirement=None,
    clan=[SpiderClan, NinjaFaction, ShadowlandsFaction],
    keywords=[Ninja, Shadowlands],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Goju_Mitsuru = Personality(
    id=12166,
    title="Goju Mitsuru",
    force=2,
    chi=2,
    personal_honor=0,
    gold_cost=4,
    honor_requirement=None,
    clan=[SpiderClan, NinjaFaction, ShadowlandsFaction],
    keywords=[Reserve, Ninja, Shadowlands],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Goju_Yurishi_Experienced_2 = Personality(
    id=12167,
    title="Goju Yurishi",
    force=4,
    chi=4,
    personal_honor=0,
    gold_cost=9,
    honor_requirement=None,
    clan=[SpiderClan, NinjaFaction, ShadowlandsFaction],
    keywords=[Experienced("2"), Unique, Daimyo, DragonChild, Ninja, Shadowlands],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Kokujin_Gunjao = Personality(
    id=12168,
    title="Kokujin Gunjao",
    force=2,
    chi=2,
    personal_honor=0,
    gold_cost=4,
    honor_requirement=None,
    clan=[SpiderClan, BrotherhoodOfShinsei, ShadowlandsFaction],
    keywords=[Duelist, Monk, Shadowlands],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Naibu = Personality(
    id=12169,
    title="Naibu",
    force=3,
    chi=3,
    personal_honor=0,
    gold_cost=4,
    honor_requirement=None,
    clan=[SpiderClan, ShadowlandsFaction],
    keywords=[Expendable, Commander, Goblin, Nonhuman, Shadowlands],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
The_Twisted_One = Personality(
    id=12170,
    title="The Twisted One",
    force=3,
    chi=3,
    personal_honor=0,
    gold_cost=5,
    honor_requirement=None,
    clan=[SpiderClan, NinjaFaction, ShadowlandsFaction],
    keywords=[Ninja, Shadowlands],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
