from __future__ import annotations

from l5r_auto.keywords import (
    GeishaHouse,
    Library,
    Market,
    Mine,
    Port,
    Stables,
    Swamp,
    Temple,
)
from l5r_auto.legality import (
    CelestialEdition,
    DiamondEdition,
    EmperorEdition,
    GoldEdition,
    ImperialEdition,
    IvoryEdition,
    JadeEdition,
    LotusEdition,
    ModernEdition,
    SamuraiEdition,
    TwentyFestivalsEdition,
)

from .common import Holding

Copper_Mine = Holding(
    card_id=1497,
    title="Copper Mine",
    gold_cost=2,
    keywords=[Mine],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        ImperialEdition,
        CelestialEdition,
        GoldEdition,
        JadeEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Deeds_and_Words = Holding(
    card_id=1914,
    title="Deeds and Words",
    gold_cost=2,
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        CelestialEdition,
        SamuraiEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Family_Library = Holding(
    card_id=2463,
    title="Family Library",
    gold_cost=2,
    keywords=[Library],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Geisha_House = Holding(
    card_id=2784,
    title="Geisha House",
    gold_cost=2,
    keywords=[GeishaHouse],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        ImperialEdition,
        CelestialEdition,
        GoldEdition,
        JadeEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Gold_Mine = Holding(
    card_id=2867,
    title="Gold Mine",
    gold_cost=2,
    keywords=[Mine],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        ImperialEdition,
        CelestialEdition,
        GoldEdition,
        JadeEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Iron_Mine = Holding(
    card_id=3808,
    title="Iron Mine",
    gold_cost=2,
    keywords=[Mine],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        ImperialEdition,
        CelestialEdition,
        GoldEdition,
        JadeEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Kobune_Port = Holding(
    card_id=4496,
    title="Kobune Port",
    gold_cost=2,
    keywords=[Port],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        CelestialEdition,
        GoldEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Marketplace = Holding(
    card_id=4840,
    title="Marketplace",
    gold_cost=2,
    keywords=[Market],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        ImperialEdition,
        CelestialEdition,
        GoldEdition,
        JadeEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Shinomen_Marsh = Holding(
    card_id=6984,
    title="Shinomen Marsh",
    gold_cost=2,
    keywords=[Swamp],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        CelestialEdition,
        SamuraiEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Shrine_to_Hachiman = Holding(
    card_id=7223,
    title="Shrine to Hachiman",
    gold_cost=2,
    keywords=[Temple],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Silver_Mine = Holding(
    card_id=7266,
    title="Silver Mine",
    gold_cost=2,
    keywords=[Mine],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        ImperialEdition,
        CelestialEdition,
        GoldEdition,
        JadeEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
Stables = Holding(
    card_id=7443,
    title="Stables",
    gold_cost=2,
    keywords=[Stables],
    traits=[],
    abilities=[],
    legality=[
        IvoryEdition,
        TwentyFestivalsEdition,
        EmperorEdition,
        LotusEdition,
        ImperialEdition,
        CelestialEdition,
        GoldEdition,
        JadeEdition,
        SamuraiEdition,
        DiamondEdition,
        ModernEdition,
        ModernEdition,
    ],
)
