from __future__ import annotations
from .common import Sensei
from l5r_auto.keywords import AllClans, Crab, Crane, Dragon, Lion, Mantis, Phoenix, Scorpion, Spider, Unicorn
from l5r_auto.legality import IvoryEdition, ModernEdition, TwentyFestivalsEdition
'Your Ancestors have -1F while attacking. <br><b>Interrupt, :bow:, :g3::</b> After the action Recruits your Lion Clan Shugenja, create a 2F/2C/3PH <b>Lion Clan &#149; Ancestor &#149; Samurai &#149; Spirit</b> Personality and gain 1 Honor.'
Kagako_Sensei = Sensei(card_id=11700, title='Kagako Sensei', gold_production='+0', starting_family_honor=0, province_strength=-1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Your Kolat cards have <b>Expendable</b>. Before another player's turn ends, gain a <b>Conspiracy</b> token if he controls no unbowed Personalities. You win the game if you ever have ten Conspiracy tokens.<br>After a Personality is Recruited, you may bow this Sensei to <i>kidnap him</i>; bow him and after the next turn begins, straighten him."
Kobi_Sensei = Sensei(card_id=11647, title='Kobi Sensei', gold_production='+0', starting_family_honor=-2, province_strength=0, keywords=[AllClans], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'You may only Recruit Personalities and Equip Spells that are Fire.<br><b>Battle, :bow::</b> Destroy your target Fire card. Ranged 3 Attack.'
Koiso_Sensei = Sensei(card_id=11701, title='Koiso Sensei', gold_production='+0', starting_family_honor=0, province_strength=0, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"After a card attacks you or one of its actions resolves, you may discard a Clout token from it to gain 2 Honor.<br><b>Political Open, :bow::</b> Bow your target unbowed Courtier. Give another player's target card a <b>Clout </b>token."
Kuroko_Sensei = Sensei(card_id=11702, title='Kuroko Sensei', gold_production='-1', starting_family_honor=2, province_strength=0, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'After your action creates a Spirit, once per turn you may target and bow your unbowed Shugenja to gain 1 Honor.<br><b>Absent Battle, :bow::</b> If there are any attacking enemy units at the current battlefield, bow your target unbowed Shugenja at any location to move your target Spirit Personality at any location there. Straighten him as he moves.'
Ohsuki_Sensei = Sensei(card_id=11703, title='Ohsuki Sensei', gold_production='-1', starting_family_honor=2, province_strength=0, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Your Stronghold has no abilities. Your Geisha enter play for 1 less Gold. <br><b>Interrupt, :bow::</b> After the action shows cards in another player's hand, choose one of them. He may discard it; if he doesn't, he cannot play cards with that title this turn."
Sachina_Sensei = Sensei(card_id=11648, title='Sachina Sensei', gold_production='+0', starting_family_honor=0, province_strength=1, keywords=[Crane, Mantis, Scorpion], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Recruiting Personalities has a minimum Gold Cost of 5 for you. You may bow your target unbowed Courtier instead of discarding the Imperial Favor for Favor actions.'
Shibata_Sensei = Sensei(card_id=11704, title='Shibata Sensei', gold_production='+0', starting_family_honor=0, province_strength=0, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"You cannot gain Honor from Holdings. After another player refuses your challenge, gain 1 Honor.<br><b>Interrupt, :bow::</b> After you win the action's duel, draw a card."
Tadanobu_Sensei = Sensei(card_id=11705, title='Tadanobu Sensei', gold_production='+0', starting_family_honor=0, province_strength=0, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Your Stronghold has no abilities. After another player resolves an action or trait, or produces gold, from his Holding with a Wealth token, you gain 1 Honor and he may discard the token. <br><b>Economic Open, :bow::</b> Give another player's target Holding a +1GP <b>Wealth </b>token."
Takeru_Sensei = Sensei(card_id=11706, title='Takeru Sensei', gold_production='+0', starting_family_honor=0, province_strength=0, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"You may only Proclaim Shugenja. Your Earth Personalities have +1F while defending.<br><b>Open, :bow::</b> If it is another player's turn and he controls a Personality, gain 2 Honor before this turn ends if you did not lose any Provinces between now and then."
Tamoko_Sensei = Sensei(card_id=11707, title='Tamoko Sensei', gold_production='-1', starting_family_honor=0, province_strength=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Increase Fear strength bonuses and penalties from your Courage actions by 1.<br><b>Battle, :bow::</b> Fear 0.'
Tanizaki_Sensei = Sensei(card_id=11649, title='Tanizaki Sensei', gold_production='+0', starting_family_honor=-1, province_strength=-1, keywords=[Crab, Lion, Spider, Unicorn], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Your Stronghold has no abilities or traits. Your non-Courtier Personalities enter play for 1 more Gold. Your Political abilities in and out of play have <b>Economic</b>. Your Iron Mines in and out of play have <b>Market</b>.<br><b>Economic Open, :bow::</b> Target a Holding. After the next time this turn it bows, its controller loses 1 Honor.'
Tsujiken_Sensei = Sensei(card_id=11708, title='Tsujiken Sensei', gold_production='+1', starting_family_honor=0, province_strength=0, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'The rulebook Kharmic ability is <b>Battle/Open</b> for you, and you may put cards at the bottom of your deck instead of discarding them from that ability. Your Personalities in and out of play have <b>Kharmic</b>.<br><b>Open, :bow::</b> Ignore the Gold cost of your next Kharmic action.'
Yung_Sensei = Sensei(card_id=11650, title='Yung Sensei', gold_production='-1', starting_family_honor=0, province_strength=0, keywords=[Dragon, Phoenix], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])