from __future__ import annotations

from l5r_auto.cards.personalities.common import Personality
from l5r_auto.clans import MantisClan
from l5r_auto.keywords import (
    BountyHunter,
    ClanChampion,
    Earth,
    Experienced,
    Kensai,
    Loyal,
    Magistrate,
    Naval,
    Samurai,
    Scout,
    Shugenja,
    SoulOf,
    TheGrowingStorm,
    Thunder,
    Unique,
)
from l5r_auto.legality import IvoryEdition, ModernEdition, TwentyFestivalsEdition

Kitsune_Parumba = Personality(
    id=11188,
    title="Kitsune Parumba",
    force=0,
    chi=2,
    honor_requirement=2,
    personal_honor=3,
    gold_cost=8,
    clan=[MantisClan],
    keywords=[Earth, Shugenja],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Moshi_Madohime = Personality(
    id=11189,
    title="Moshi Madohime",
    force=2,
    chi=2,
    honor_requirement=0,
    personal_honor=2,
    gold_cost=4,
    clan=[MantisClan],
    keywords=[Naval, Scout, Shugenja, Thunder],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Tsuruchi_Kaito = Personality(
    id=11190,
    title="Tsuruchi Kaito",
    force=2,
    chi=2,
    honor_requirement=None,
    personal_honor=1,
    gold_cost=6,
    clan=[MantisClan],
    keywords=[Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Tsuruchi_Natsuki = Personality(
    id=11191,
    title="Tsuruchi Natsuki",
    force=4,
    chi=3,
    honor_requirement=0,
    personal_honor=2,
    gold_cost=7,
    clan=[MantisClan],
    keywords=[Magistrate, Samurai, SoulOf("Tsuruchi Masako")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Tsuruchi_Rin = Personality(
    id=11192,
    title="Tsuruchi Rin",
    force=2,
    chi=3,
    honor_requirement=None,
    personal_honor=2,
    gold_cost=5,
    clan=[MantisClan],
    keywords=[BountyHunter, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Yoritomo_Hiromi_the_Growing_Storm_Experienced_2 = Personality(
    id=11193,
    title="Yoritomo Hiromi, the Growing Storm",
    force=4,
    chi=5,
    honor_requirement=4,
    personal_honor=3,
    gold_cost=10,
    clan=[MantisClan],
    keywords=[
        Experienced("2"),
        Kensai,
        Loyal,
        Naval,
        Unique,
        ClanChampion,
        Samurai,
        TheGrowingStorm,
        Thunder,
    ],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Yoritomo_Ichido = Personality(
    id=11194,
    title="Yoritomo Ichido",
    force=4,
    chi=3,
    honor_requirement=0,
    personal_honor=1,
    gold_cost=8,
    clan=[MantisClan],
    keywords=[Naval, Samurai, SoulOf("Kindari")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Yoritomo_Matsuo = Personality(
    id=11195,
    title="Yoritomo Matsuo",
    force=3,
    chi=4,
    honor_requirement=0,
    personal_honor=2,
    gold_cost=5,
    clan=[MantisClan],
    keywords=[Kensai, Naval, Samurai, SoulOf("Seppun Matsuo")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Yoritomo_Takuya = Personality(
    id=11196,
    title="Yoritomo Takuya",
    force=3,
    chi=3,
    honor_requirement=None,
    personal_honor=1,
    gold_cost=5,
    clan=[MantisClan],
    keywords=[Naval, Samurai, SoulOf("Yoritomo Bussho")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
Yoritomo_Teihiko = Personality(
    id=11197,
    title="Yoritomo Teihiko",
    force=4,
    chi=2,
    honor_requirement=None,
    personal_honor=1,
    gold_cost=5,
    clan=[MantisClan],
    keywords=[Naval, Samurai, SoulOf("Yoritomo Mie")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, IvoryEdition, ModernEdition],
)
