from __future__ import annotations

from l5r_auto.clans import LionClan
from l5r_auto.keywords import (
    ClanChampion,
    Deathseeker,
    Experienced,
    Loyal,
    Paragon,
    Samurai,
    Scout,
    SoulOf,
    Tactician,
    TheSteelLion,
    Unique,
    WarLeader,
)
from l5r_auto.legality import IvoryEdition, ModernEdition, TwentyFestivalsEdition

from ..common import Personality

Akodo_Dairuko_the_Steel_Lion_Experienced_2 = Personality(
    card_id=11178,
    title="Akodo Dairuko, the Steel Lion",
    force=4,
    chi=5,
    personal_honor=5,
    gold_cost=10,
    honor_requirement=10,
    clan=[LionClan],
    keywords=[
        Experienced("2"),
        Loyal,
        Tactician,
        Unique,
        ClanChampion,
        Paragon,
        Samurai,
        TheSteelLion,
    ],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition],
)
Akodo_Kenaro = Personality(
    card_id=11179,
    title="Akodo Kenaro",
    force=2,
    chi=4,
    personal_honor=3,
    gold_cost=5,
    honor_requirement=6,
    clan=[LionClan],
    keywords=[Tactician, Samurai, SoulOf("Akodo Ijiasu"), WarLeader],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition],
)
Ikoma_Ichimoko = Personality(
    card_id=11180,
    title="Ikoma Ichimoko",
    force=3,
    chi=2,
    personal_honor=3,
    gold_cost=5,
    honor_requirement=7,
    clan=[LionClan],
    keywords=[Samurai, Scout],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Ikoma_Yoshimoko = Personality(
    card_id=11181,
    title="Ikoma Yoshimoko",
    force=3,
    chi=2,
    personal_honor=2,
    gold_cost=5,
    honor_requirement=5,
    clan=[LionClan],
    keywords=[Samurai, Scout],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Matsu_Agai = Personality(
    card_id=11182,
    title="Matsu Agai",
    force=2,
    chi=2,
    personal_honor=2,
    gold_cost=4,
    honor_requirement=5,
    clan=[LionClan],
    keywords=[Deathseeker, Samurai, SoulOf("Matsu Agoro")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Matsu_Choiko = Personality(
    card_id=11183,
    title="Matsu Choiko",
    force=2,
    chi=2,
    personal_honor=2,
    gold_cost=6,
    honor_requirement=8,
    clan=[LionClan],
    keywords=[Samurai, SoulOf("Matsu Ryoichi")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Matsu_Morito = Personality(
    card_id=11185,
    title="Matsu Morito",
    force=4,
    chi=2,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=2,
    clan=[LionClan],
    keywords=[Deathseeker, Samurai, SoulOf("Matsu Sanraku")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Matsu_Rutaro = Personality(
    card_id=11186,
    title="Matsu Rutaro",
    force=4,
    chi=3,
    personal_honor=2,
    gold_cost=6,
    honor_requirement=0,
    clan=[LionClan],
    keywords=[Samurai, SoulOf("Matsu Turi")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Matsu_Tayuko = Personality(
    card_id=11187,
    title="Matsu Tayuko",
    force=1,
    chi=3,
    personal_honor=3,
    gold_cost=3,
    honor_requirement=6,
    clan=[LionClan],
    keywords=[Samurai, SoulOf("Matsu Aoiko")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
