from __future__ import annotations

from l5r_auto.clans import LionClan, SpiritFaction
from l5r_auto.keywords import (
    Ancestor,
    Cavalry,
    ChildOfProphecy,
    Commander,
    Destined,
    Duelist,
    Experienced,
    Hero,
    LoveLetter,
    Magistrate,
    Naval,
    Paragon,
    Samurai,
    Scout,
    Shugenja,
    Spirit,
    Tactician,
    TheMaskedLion,
    Water,
)
from l5r_auto.legality import IvoryEdition, ModernEdition, TwentyFestivalsEdition

from ..common import Personality

Akodo_Raikitsu = Personality(
    id=11902,
    title="Akodo Raikitsu",
    force=2,
    chi=3,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=6,
    clan=[LionClan],
    keywords=[Duelist, Tactician, Samurai],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, ModernEdition, TwentyFestivalsEdition],
)
Akodo_Yuyama = Personality(
    id=11905,
    title="Akodo Yuyama",
    force=2,
    chi=2,
    personal_honor=3,
    gold_cost=5,
    honor_requirement=6,
    clan=[LionClan, SpiritFaction],
    keywords=[Destined, Ancestor, Samurai, Scout, Spirit, TheMaskedLion],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, ModernEdition, TwentyFestivalsEdition],
)
Ikoma_Ayumi_Experienced = Personality(
    id=11903,
    title="Ikoma Ayumi",
    force=4,
    chi=3,
    personal_honor=1,
    gold_cost=7,
    honor_requirement=0,
    clan=[LionClan],
    keywords=[Cavalry, Naval, Experienced("1"), Hero, Magistrate, Samurai],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, ModernEdition, TwentyFestivalsEdition],
)
Kitsu_Suzaki = Personality(
    id=11904,
    title="Kitsu Suzaki",
    force=0,
    chi=4,
    personal_honor=3,
    gold_cost=5,
    honor_requirement=7,
    clan=[LionClan],
    keywords=[ChildOfProphecy, Shugenja, Water],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, ModernEdition, TwentyFestivalsEdition],
)
Matsu_Hachiro_Experienced = Personality(
    id=11906,
    title="Matsu Hachiro",
    force=2,
    chi=3,
    personal_honor=4,
    gold_cost=9,
    honor_requirement=10,
    clan=[LionClan],
    keywords=[Cavalry, Commander, Experienced("1"), Paragon, Samurai, Scout],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, ModernEdition, TwentyFestivalsEdition],
)
Matsu_Misato_the_Hatamoto = Personality(
    id=11907,
    title="Matsu Misato, the Hatamoto",
    force=3,
    chi=3,
    personal_honor=3,
    gold_cost=5,
    honor_requirement=7,
    clan=[LionClan],
    keywords=[LoveLetter, Samurai],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, ModernEdition, TwentyFestivalsEdition],
)
