from __future__ import annotations

from l5r_auto.clans import LionClan
from l5r_auto.keywords import (
    Beastmaster,
    Cavalry,
    Commander,
    Conqueror,
    Daimyo,
    Deathseeker,
    Duelist,
    Experienced,
    Governor,
    Hero,
    Loyal,
    Paragon,
    Samurai,
    SoulOf,
    Tactician,
    Unique,
)
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition

from ..common import Personality

Akodo_Eirasu = Personality(
    id=12114,
    title="Akodo Eirasu",
    force=4,
    chi=3,
    personal_honor=0,
    gold_cost=7,
    honor_requirement=0,
    clan=[LionClan],
    keywords=[Deathseeker, Hero, Samurai, SoulOf("Akodo Ebiro")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Akodo_Hio = Personality(
    id=12115,
    title="Akodo Hio",
    force=3,
    chi=3,
    personal_honor=2,
    gold_cost=6,
    honor_requirement=4,
    clan=[LionClan],
    keywords=[Beastmaster, Samurai, SoulOf("Akodo Michio")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Akodo_Kenaro_Experienced = Personality(
    id=12116,
    title="Akodo Kenaro",
    force=3,
    chi=4,
    personal_honor=4,
    gold_cost=9,
    honor_requirement=10,
    clan=[LionClan],
    keywords=[Duelist, Tactician, Unique, Experienced("1"), Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Akodo_Naikiru = Personality(
    id=12117,
    title="Akodo Naikiru",
    force=3,
    chi=4,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=7,
    clan=[LionClan],
    keywords=[Tactician, Governor, Samurai, SoulOf("Akodo Nakama")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Akodo_Shaido = Personality(
    id=12118,
    title="Akodo Shaido",
    force=1,
    chi=3,
    personal_honor=2,
    gold_cost=3,
    honor_requirement=7,
    clan=[LionClan],
    keywords=[Duelist, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Akodo_Taiketsu = Personality(
    id=12119,
    title="Akodo Taiketsu",
    force=2,
    chi=4,
    personal_honor=3,
    gold_cost=5,
    honor_requirement=7,
    clan=[LionClan],
    keywords=[Duelist, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Ikoma_Noritsu = Personality(
    id=12120,
    title="Ikoma Noritsu",
    force=3,
    chi=3,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=5,
    clan=[LionClan],
    keywords=[Tactician, Samurai, SoulOf("Ikoma Tatsunori")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Ikoma_Sairei = Personality(
    id=12121,
    title="Ikoma Sairei",
    force=4,
    chi=3,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=7,
    clan=[LionClan],
    keywords=[Paragon, Samurai, SoulOf("Ikoma Sido")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Matsu_Ataruko = Personality(
    id=12122,
    title="Matsu Ataruko",
    force=3,
    chi=2,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=4,
    clan=[LionClan],
    keywords=[Beastmaster, Commander, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Matsu_Chizuki = Personality(
    id=12123,
    title="Matsu Chizuki",
    force=4,
    chi=3,
    personal_honor=3,
    gold_cost=10,
    honor_requirement=8,
    clan=[LionClan],
    keywords=[Conqueror, Loyal, Unique, Beastmaster, Commander, Daimyo, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Matsu_Iairimi = Personality(
    id=12124,
    title="Matsu Iairimi",
    force=3,
    chi=3,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=6,
    clan=[LionClan],
    keywords=[Hero, Samurai, SoulOf("Matsu Mari")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Matsu_Karoko = Personality(
    id=12125,
    title="Matsu Karoko",
    force=3,
    chi=2,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=7,
    clan=[LionClan],
    keywords=[Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Matsu_Keiasu = Personality(
    id=12126,
    title="Matsu Keiasu",
    force=2,
    chi=2,
    personal_honor=2,
    gold_cost=4,
    honor_requirement=6,
    clan=[LionClan],
    keywords=[Cavalry, Beastmaster, Commander, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Matsu_Seijuko = Personality(
    id=12127,
    title="Matsu Seijuko",
    force=3,
    chi=3,
    personal_honor=2,
    gold_cost=5,
    honor_requirement=8,
    clan=[LionClan],
    keywords=[Duelist, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
