from __future__ import annotations
from .common import Strategy
from l5r_auto.keywords import Air, Allegiance, Courage, Fire, Kata, Kharmic, Kiho, Political, Terrain
from l5r_auto.legality import IvoryEdition, ModernEdition, TwentyFestivalsEdition
"<b>Battle:</b> Target your unbowed Personality. Remove an ability and a boldface keyword <i>(if able)</i> on a card in a target enemy unit. If your Personality is a Kensai, you may bow one of his Weapons to either draw a card, or search your deck for A Kensai's Will, show it, and put it in your hand. You may take an additional action to play A Kensai's Will."
A_Kensais_Art = Strategy(card_id=11660, title="A Kensai's Art", focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Battle:</b> Bow your target unbowed Personality. Melee Attack equal to his Force minus two. If your Personality was targeted by your A Kensai's Art and A Kensai's Will this turn, you may discard a card to straighten his unit."
A_Kensais_Victory = Strategy(card_id=11661, title="A Kensai's Victory", focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Battle:</b> Target your unbowed Personality. Give a target enemy Follower or Personality -3F. If your Personality was targeted by your A Kensai's Art this turn and he is a Kensai, you may bow his Weapon to either draw a card or search your deck for A Kensai's Victory, show it, and put it in your hand. You may take an additional action to play A Kensai's Victory."
A_Kensais_Will = Strategy(card_id=11662, title="A Kensai's Will", focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Air Kiho Battle:</b> Target your unbowed Monk or Shugenja. You may bow him. Move home a target Personality with Force less than or equal to your Monk or Shugenja's Chi, or his Chi plus 3 if you bowed him."
Banishing_Breath = Strategy(card_id=11663, title='Banishing Breath', focus_value=3, keywords=[Air, Kiho], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Bow your target unbowed Samurai. Melee Attack equal to his Chi, plus one if your Allegiance is Traditionalist. Gain 1 Honor.'
Benefits_of_Honor = Strategy(card_id=11664, title='Benefits of Honor', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Political Open, :g2::</b> Bow your target unbowed Courtier. Look at a number of cards on the top of your Fate deck equal to his Chi. You may put one at the bottom of your deck. Put the rest back in any order. Draw a card.'
Beset_from_All_Sides = Strategy(card_id=11665, title='Beset from All Sides', focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Fear 4, or Fear equal to the highest Force of any of your unbowed Oni at this battlefield. This may target a Lion Clan Personality with Followers. Lose 2 Honor.<br><b>Open, :g2::</b> Destroy a target Farm. Lose 2 Honor.'
Calculated_Risk = Strategy(card_id=11666, title='Calculated Risk', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Interrupt, :g2::</b> Instead of gaining Honor when you Proclaim, draw cards equal to half the Honor you would have gained, rounded up.'
Casting_Aside_Honor = Strategy(card_id=11667, title='Casting Aside Honor', focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Samurai at this battlefield have -1F. You have the ability, "<b>Repeatable Battle:</b> Move your target defending Courtier home."<br><b>Political Battle:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play. You may take an additional action.'
Combat_at_Court = Strategy(card_id=11668, title='Combat at Court', focus_value=3, keywords=[Political, Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Discipline :g4: <i>(You may pay 4 Gold to play this Discipline from your discard pile, then remove it from the game after its action resolves.)</i><br><b>Political Open:</b> Target another player's Personality. After the next time this turn he attacks, his controller discards a card <i>(if able)</i> and you draw a card."
Diplomacy_Breaks_Down = Strategy(card_id=11669, title='Diplomacy Breaks Down', focus_value=4, keywords=[Political], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Open:</b> Put this Kata into play. Discard your other Kata in play.<br><b>Battle, :bow::</b> Move your target Personality home. Lose 1 Honor.'
Disappearing_World_Style = Strategy(card_id=11670, title='Disappearing World Style', focus_value=2, keywords=[Kharmic, Kata], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'After your action resolves, if it bowed any enemy cards, gain 1 Honor.<br><b>Battle/Engage:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play.'
Familiar_Terrain = Strategy(card_id=11671, title='Familiar Terrain', focus_value=3, keywords=[Kharmic, Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<i>(<b>Repeatable Interrupt:</b> Discard a Courage card to give a Fear effect +2 or -2 strength.)</i><br><b>Battle:</b> Straighten your target opposed card. Gain 1 Honor.'
Fearless_Devotion = Strategy(card_id=11672, title='Fearless Devotion', focus_value=1, keywords=[Courage], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<i>(<b>Repeatable Interrupt:</b> Discard a Courage card to give a Fear effect +2 or -2 strength.)</i><br><b>Absent Battle:</b> If he would be opposed, move your target unbowed Personality in your home to the current battlefield. <i>(Absent actions may be taken without presence.)</i>'
Flight_of_No_Mind = Strategy(card_id=11673, title='Flight of No Mind', focus_value=3, keywords=[Courage], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Before the Action Phase ends, you may take an additional action.<br><b>Political Open:</b> Put this Kata into play. Discard your other Kata in play.<br><b>Open, :bow::</b> Look at the top card of your Fate deck. You may put it at the bottom.'
Hidden_Machinations = Strategy(card_id=11674, title='Hidden Machinations', focus_value=4, keywords=[Kharmic, Kata, Political], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Discipline :g3: <i>(You may :g3: to play this Discipline from your discard pile, then remove it from the game after its action resolves.)</i><br><b>Battle:</b> Move home a target Personality with the highest Personal Honor at the current battlefield <i>(you choose in case of a tie)</i>.'
Ideological_Differences = Strategy(card_id=11675, title='Ideological Differences', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<i>(<b>Repeatable Limited, :g2::</b> Discard a Kharmic card to draw a card.)</i> <br><b>Open:</b> Put a non-Fudo Ring into play from your hand. While it remains in play, it does not count towards an Enlightenment Victory.'
Long_Term_Fruition = Strategy(card_id=11676, title='Long Term Fruition', focus_value=1, keywords=[Kharmic], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> You may use the Battle abilities of your target card in a unit one additional time this turn. If you targeted a Yojimbo, you may target and bow your Courtier or Shugenja at any location to straighten the Yojimbo.'
Not_Yet_Finished = Strategy(card_id=11677, title='Not Yet Finished', focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Invest :g3:<b>:</b> Draw a card. <i>(After you play this card, you may also pay the Invest cost to get the effect, once.)</i><br><b>Open:</b> Straighten your target Personality, or straighten his unit if he is a Duelist.'
Ornery = Strategy(card_id=11678, title='Ornery', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Move your target Personality home and straighten his unit as he moves. You may target a Personality and give him +2F or -2F.'
Planned_Departure = Strategy(card_id=11679, title='Planned Departure', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Battle:</b> Target a non-Ring card in another player's discard pile. If the card was discarded by a Strike First this turn, put it in your hand, and you may target your Scout and discard a card to search your deck for a Show No Mercy, show it, and put it in your hand; otherwise, remove the first target from the game. You may take an additional action to play Show No Mercy."
Press_the_Advantage = Strategy(card_id=11680, title='Press the Advantage', focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'You may not play other Allegiance cards. <br><b>Political Open:</b> Put this Strategy into play.<br><b>Absent Political Battle, :bow::</b> Discard any number of cards to move home a target enemy unit with total Force less than or equal to the total Focus Values of the discarded cards.'
Progressive = Strategy(card_id=11681, title='Progressive', focus_value=4, keywords=[Kharmic, Allegiance, Political], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Fire Kiho Battle:</b> Melee Attack equal to your target Monk or Shugenja's Force or Chi. Destroy that Monk or Shugenja."
Redirecting_Rage = Strategy(card_id=11682, title='Redirecting Rage', focus_value=2, keywords=[Fire, Kiho], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard a Courage card to give a Fear effect +2 or -2 strength.)</i><br><b>Battle:</b> Target a Personality. Negate his <i>(current)</i> Force bonuses or penalties.<br><b>Battle:</b> Give <b>Resilient</b> to, or remove <b>Resilient</b> from, a target Personality.'
Sanctioned_Declaration = Strategy(card_id=11683, title='Sanctioned Declaration', focus_value=2, keywords=[Courage], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Target your unbowed Personality, and bow him unless he was targeted by Strike First and Press the Advantage this turn. Ranged 3 Attack. You may take an additional action to play or Equip a card from your hand that you do not own.'
Show_No_Mercy = Strategy(card_id=11684, title='Show No Mercy', focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Open:</b> Put this Kata into play. Discard your other Kata in play. <br><b>Interrupt, :bow::</b> The action's Fear effects may target Items and destroy attachments after bowing them."
Show_of_Power = Strategy(card_id=11685, title='Show of Power', focus_value=2, keywords=[Courage, Kata], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"As a Focus Effect, you may choose to lose this duel to negate its consequences for losing.<br><b>Invest :g2::</b> Resolve this action's targeting and effects a second time.<br><b>Political Open:</b> Rehonor your target Personality.<br><b>Open, :g2::</b> Put a target attachment in your discard pile into your hand."
Spirited_Dispute = Strategy(card_id=11686, title='Spirited Dispute', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Iaijutsu Battle:</b> Your target unbowed Personality challenges a target enemy Personality. Give the loser -3F. If the winner is a Duelist, give him a +1F token.'
Startling_Lessons = Strategy(card_id=11687, title='Startling Lessons', focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Battle:</b> Target your unbowed Personality. Give a target enemy Personality a Force penalty equal to your Personality's Chi. If your Personality is a Yojimbo, you may target a Courtier or Shugenja at any location and give all his abilities Home <i>(this turn)</i>."
Step_Into_the_Fray = Strategy(card_id=11688, title='Step Into the Fray', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Your Fear effects have +1 strength and may target Personalities with Followers.<br><b>Battle/Engage:</b> Destroy a target Terrain <i>(if able)</i>. Put this Terrain into play.'
Streets_of_the_Second_City = Strategy(card_id=11689, title='Streets of the Second City', focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Your minimum Fate deck size is increased by two.<br>As a Focus Effect, after you win this duel, shuffle zero to three cards in your Fate discard pile into your deck.<br><b>Iaijutsu Battle:</b> Your target unbowed Personality challenges a target enemy Personality. His controller must focus at least once from his hand <i>(if able)</i>. Move the loser home.'
Strength_Remains = Strategy(card_id=11690, title='Strength Remains', focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Battle:</b> Show two random cards in another player's hand. You may discard one of them; if you do, he draws a card. You may target your unbowed Scout to search your deck for Press the Advantage, show it, and put it in your hand. You may take an additional action to play Press the Advantage."
Strike_First = Strategy(card_id=11691, title='Strike First', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Target one or two of your opposed Personalities. Give them each +1F, or +2F if they are defending.'
Strike_to_Both_Sides = Strategy(card_id=11692, title='Strike to Both Sides', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"You may not play other Allegiance cards. Your Favor actions may target your Personalities as well as other players'.<br><b>Political Open:</b> Put this Strategy into play.<br><b>Political Interrupt, :bow::</b> If the action is Favor and is targeting your Personality, its player must choose a different target, if legal."
Traditionalist = Strategy(card_id=11693, title='Traditionalist', focus_value=4, keywords=[Courage, Allegiance], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Political Open, :g2::</b> Target another player. <i>You accuse him of covertly preparing for war.</i> Choose one to three random cards from his hand and show them. For each of these cards that is a Weapon or has a Battle or Engage ability, he loses 1 Honor, plus 1 additional Honor if your Allegiance is Progressive. For each other shown card, he gains 1 Honor.'
Uncovered_Plans = Strategy(card_id=11694, title='Uncovered Plans', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard a Courage card to give a Fear effect +2 or -2 strength.)</i><br>Favor actions may not be taken. This Province has a maximum strength equal to its printed value.<br><b>Battle/Engage:</b> Destroy a Terrain <i>(if able)</i>. Lose 1 Honor. Put this Terrain into play.'
Untouched_Lands = Strategy(card_id=11695, title='Untouched Lands', focus_value=2, keywords=[Courage, Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Absent Battle:</b> Target your Personality at any battlefield <i>(not your home)</i>. Move him home or, if he would be opposed, to the current battlefield. You may take an additional action to use an ability on a card in his unit. <i>(Absent actions may be taken without presence.)</i>'
Unwavering_Resolve = Strategy(card_id=11696, title='Unwavering Resolve', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'As a Focus Effect, after you win this duel, remove one to three non-Ring cards in discard piles from the game.<br><b>Invest :g1::</b> Draw a card.<br><b>Battle/Open:</b> Remove one to three non-Ring cards in discard piles from the game. You may target a Personality and remove one of his abilities or boldface keywords <i>(this turn)</i>. Take an additional action.'
Victory_Through_Deference = Strategy(card_id=11697, title='Victory Through Deference', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'As a Focus Effect, after you win this duel, draw a card.<br><b>Invest :g2::</b> If the Sensei is yours, you may use its abilities a second time this turn.<br><b>Open:</b> Bow or straighten a target Sensei.'
Your_Past = Strategy(card_id=11698, title='Your Past', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle/Open, :gstar::</b> Destroy a target attachment with Gold Cost less than or equal to the amount paid, or the amount paid plus three if the target is an Item.'
Your_True_Nature = Strategy(card_id=11699, title='Your True Nature', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])