from __future__ import annotations
from .common import Strategy
from l5r_auto.keywords import Air, BushidoVirtue, Compassion, DarkVirtue, Duty, Favor, Fear, Fire, Iaijutsu, Imperial, Insight, Kiho, Kolat, Ninja, Political, Recon, Siege, Tactical, Tattoo, Terrain, Unique, Void, Will
from l5r_auto.legality import CelestialEdition, DiamondEdition, EmperorEdition, GoldEdition, ImperialEdition, IvoryEdition, JadeEdition, LotusEdition, ModernEdition, OnyxEdition, SamuraiEdition, TwentyFestivalsEdition
'<b>Limited:</b> Gain 3 Honor, or 1 Honor for each Ancestor you have in play, whichever is lower.<br><b>Battle:</b> Destroy your target performing unbowed Ancestor to destroy a target enemy card without attachments.'
A_Forefathers_Vengeance = Strategy(card_id=23, title="A Forefather's Vengeance", gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> Target your performing unbowed Paragon. Ranged Attack with strength equal to his Force. Lose 4 Honor.<br><b>Battle:</b> Target your performing unbowed Paragon and target an enemy Personality with equal or lower Personal Honor. Move him home. Gain 2 Honor.'
A_Paragons_Strength = Strategy(card_id=61, title="A Paragon's Strength", gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open:</b> Target a Weapon: Raise its Force and Chi modifiers to twice its base Force and Chi modifiers <i>(this does not affect negative base modifiers)</i>.'
A_Pure_Stroke = Strategy(card_id=68, title='A Pure Stroke', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, JadeEdition, ModernEdition])
"<b>Battle, :gstar::</b> Target your performing unbowed Magistrate to target an enemy card without attachments with Gold Cost equal to what you paid minus 2 or an enemy Personality whose unit's total Gold Cost is equal what you paid minus 2. Destroy the card or unit."
A_Stain_Cleansed = Strategy(card_id=82, title='A Stain Cleansed', focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open:</b> Destroy your target performing Ancestor to give your target Personality +3F.'
A_Time_for_Mortal_Men = Strategy(card_id=90, title='A Time for Mortal Men', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, JadeEdition, ModernEdition])
"<b>Limited:</b> Target your unbowed Personality and another player's Personality. Create a battlefield <i>(not at any Province)</i>. Assign your Personality to attack there. Assign the other Personality to defend there, even if he is bowed. Other Personalities cannot move there. Fight a battle there <i>(after this action resolves)</i>. After the battle ends, lose 5 Honor."
Ambush = Strategy(card_id=344, title='Ambush', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, LotusEdition, ImperialEdition, CelestialEdition, GoldEdition, JadeEdition, SamuraiEdition, DiamondEdition, ModernEdition])
"<b>Reaction:</b> After an action targets your Personality, destroy your target performing Ancestor to negate the action's effects."
Ancestral_Protection = Strategy(card_id=370, title='Ancestral Protection', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, GoldEdition, JadeEdition, ModernEdition])
'<b>Ninja Limited:</b> Target your performing Saboteur or Ninja Personality to discard a Dynasty card in a Province and lose 2 Honor.'
Aramoros_Promise = Strategy(card_id=424, title="Aramoro's Promise", gold_cost=0, focus_value=2, keywords=[Ninja], traits=[], abilities=[], legality=[EmperorEdition, GoldEdition, DiamondEdition, ModernEdition])
'<b>Dark Virtue Battle, :gstar::</b> Recruit your target performing dead Samurai.'
At_Any_Cost = Strategy(card_id=639, title='At Any Cost', gold_cost=0, focus_value=1, keywords=[DarkVirtue, Will], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Iaijutsu Battle:</b> Your target unbowed Personality challenges a target enemy Personality. Bow the loser. The winning player may create a 2F/2C/2PH Samurai Personality with his Clan Alignment.'
Awed_Witness = Strategy(card_id=657, title='Awed Witness', focus_value=3, traits=[], abilities=[], legality=[TwentyFestivalsEdition, EmperorEdition, CelestialEdition, OnyxEdition, ModernEdition])
'<b>Absent Battle:</b> Target your Personality at any location who assigned to this battlefield <i>(this turn)</i>. Move him there and straighten his unit as he moves. <i>(You may take Absent actions without presence.)</i>'
Back_to_the_Front = Strategy(card_id=662, title='Back to the Front', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> After another player with Family Honor of -1 or lower announces an action on a Strategy: He ignores the action's costs. Negate its effects."
Bad_Kharma = Strategy(card_id=663, title='Bad Kharma', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, ImperialEdition, JadeEdition, ModernEdition])
'<b>Tactical Limited:</b> Target your performing unbowed Tactician to look at the top four cards of your Fate deck. Put one of them in your hand and put the other three on the bottom of your deck in any order.'
Banish_All_Doubt = Strategy(card_id=690, title='Banish All Doubt', gold_cost=0, focus_value=3, keywords=[Tactical], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'You may only play one copy of Bend like a Reed per duel.<br><b>Reaction:</b> Before Focus Effects resolve, if your target performing Personality in the duel did not strike, give him +2 to his duel stat until the duel ends.'
Bend_like_a_Reed = Strategy(card_id=954, title='Bend like a Reed', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, ImperialEdition, GoldEdition, JadeEdition, ModernEdition])
"<b>Open:</b> Destroy a performing Personality you own and control: Increase or decrease the strength of all players' provinces by an amount equal to the Personality's base Chi."
Besieged = Strategy(card_id=963, title='Besieged', gold_cost=0, focus_value=4, keywords=[Unique, Siege], traits=[], abilities=[], legality=[EmperorEdition, SamuraiEdition, ModernEdition])
'<b>Battle:</b> Give your target performing unbowed Berserker +5F. Lose 2 Honor.'
Blind_Rage = Strategy(card_id=1044, title='Blind Rage', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
'<b>Battle:</b> Move home a target attacking Personality. Bow his unit as he moves.'
Block_Supply_Lines = Strategy(card_id=1045, title='Block Supply Lines', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, ImperialEdition, GoldEdition, JadeEdition, SamuraiEdition, DiamondEdition, ModernEdition])
'<b>Fire Battle:</b> Target your performing unbowed Fire or Tattooed Personality to make a Ranged 3 Attack with +1 strength for each Fire token on your Personality and give your Personality a +1F Fire token.'
Breath_of_the_Heavens = Strategy(card_id=1135, title='Breath of the Heavens', gold_cost=0, focus_value=3, keywords=[Fire, Tattoo], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Recon Reaction:</b> After engaging, target your performing unbowed Scout Personality at the current battlefield. You have Reconnaissance there. Give its Province -3 strength.'
Burn_the_Towers = Strategy(card_id=1180, title='Burn the Towers', gold_cost=0, focus_value=1, keywords=[Recon], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> After another player's action targets one or more of your Personalities: Negate their bowing from the action's effects."
Caught_in_the_Act = Strategy(card_id=1238, title='Caught in the Act', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, SamuraiEdition, ModernEdition])
'<b>Political Interrupt:</b> Negate the effects of a Favor action, its player discards the Imperial Favor.'
Confusion_at_Court = Strategy(card_id=1450, title='Confusion at Court', gold_cost=0, focus_value=2, keywords=[Political], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, ImperialEdition, GoldEdition, JadeEdition, DiamondEdition, ModernEdition])
'<b>Battle:</b> Target your performing Personality with Scout, Tactician, or 3 or higher Chi, to destroy a target Terrain. You may take an additional Battle action to play a Terrain.'
Control_the_Field = Strategy(card_id=1487, title='Control the Field', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, GoldEdition, SamuraiEdition, DiamondEdition, ModernEdition])
'<b>Battle:</b> Target your performing unbowed Tactician to bow or straighten a target Personality with equal or lower Chi.'
Dangerous_Indulgence = Strategy(card_id=1820, title='Dangerous Indulgence', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Target your performing Commander to give your target Follower a Force bonus equal to twice its current Force. After this battle's resolution, destroy the Follower."
Deadly_Orders = Strategy(card_id=1885, title='Deadly Orders', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
'<b>Reaction:</b> After the resolution of an action that bowed a Ring: Straighten it.<br><b>Battle:</b> Target a Personality or Follower: Give it -4F. Bow it if you control a Ring.'
Deception_Revealed = Strategy(card_id=1908, title='Deception Revealed', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Open:</b> If another player has higher Family Honor than you, bow your target performing Nonhuman or Spirit to gain 3 Honor.<br><b>Battle:</b> Target your performing unbowed Nonhuman or Spirit to bow a target enemy card without attachments.'
Duel_of_Serpents = Strategy(card_id=2246, title='Duel of Serpents', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'Before this battle resolves, the Attacker and Defender, in the order of your choice, each choose one of their own Personalities at its battlefield. Move all other Personalities there home. <br><b>Battle:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play.'
Encircled_Terrain = Strategy(card_id=2332, title='Encircled Terrain', gold_cost=0, focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, LotusEdition, ImperialEdition, CelestialEdition, GoldEdition, JadeEdition, SamuraiEdition, DiamondEdition, ModernEdition])
'Before this battle resolves: You may choose and straighten a Samurai Personality at the current battlefield, and you may choose and bow a non-Samurai Personality there.<br><b>Battle:</b> If there are no Terrains at the current battlefield: Put this card into play there.'
Extended_Maneuvers = Strategy(card_id=2419, title='Extended Maneuvers', gold_cost=0, focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, CelestialEdition, SamuraiEdition, DiamondEdition, ModernEdition])
'<b>Open:</b> Shuffle your hand into your Fate deck: Draw a number of cards equal to the number you shuffled in.'
Face_of_Ninube = Strategy(card_id=2431, title='Face of Ninube', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, JadeEdition, DiamondEdition, ModernEdition])
'<b>Battle:</b> Move home your target Personality. As he moves, straighten his unit and you may straighten one of your other units <i>(at any location)</i>.'
Fall_Back = Strategy(card_id=2445, title='Fall Back!', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Monk and target an enemy Personality or Follower: Move your Monk to the current battlefield. Give the target -3F. Bow it if its Force is now 0.'
Falling_Leaf_Strike = Strategy(card_id=2454, title='Falling Leaf Strike', gold_cost=0, focus_value=3, keywords=[Kiho], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
'<b>Interrupt:</b> Target your Personality. After the action resolves, if it destroyed him, bring him into play in your home, ignoring costs and Honor Requirement, then bow him, dishonor him, and lose 2 Honor.'
Feign_Death = Strategy(card_id=2503, title='Feign Death', focus_value=2, traits=[], abilities=[], legality=[TwentyFestivalsEdition, EmperorEdition, ImperialEdition, OnyxEdition, DiamondEdition, ModernEdition])
"Before a card effect destroys a Personality in an army, if a card effect has destroyed another Personality in that army while this card was in play: Negate the Personality's destruction.<br><b>Battle:</b> If there are no Terrains at the current battlefield: Put this card into play there."
Fields_of_Mercy = Strategy(card_id=2530, title='Fields of Mercy', gold_cost=0, focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, ModernEdition])
"As a Focus Effect: After this duel ends, if your Personality won it, take the Imperial Favor.<br><b>Battle:</b> Choose your performing unbowed Duelist and target one or two Personalities whose total Chi is lower than or equal to your Duelist's Chi: Bow them."
Final_Confrontation = Strategy(card_id=2547, title='Final Confrontation', gold_cost=0, focus_value=3, keywords=[Iaijutsu, Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'This province has +2 strength for each unit in the attacking army. <br><b>Battle:</b> Even if you control no units at the current battlefield, if there are no Terrains there: Put this card into play there.'
Flooded_Pass = Strategy(card_id=2613, title='Flooded Pass', gold_cost=0, focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, JadeEdition, ModernEdition])
Focus = Strategy(card_id=2619, title='Focus', gold_cost=0, focus_value=5, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, ImperialEdition, GoldEdition, JadeEdition, SamuraiEdition, DiamondEdition, ModernEdition])
"<b>Reaction:</b> Before the resolution of an action from a Stronghold, pay Gold equal to the Stronghold's base Gold Production: Negate the action's effects."
Footsteps_of_Madness = Strategy(card_id=2629, title='Footsteps of Madness', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, JadeEdition, ModernEdition])
"<b>Battle:</b> Choose your performing unbowed Berserker and target an enemy unit with lower total Force than your Berserker's base Force: Bow the target. Negate all current and new Force penalties on your Berserker from actions."
Fortitude = Strategy(card_id=2671, title='Fortitude', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open:</b> Target one to three attachments with a Gold Cost of 0: Destroy them.<br><b>Battle:</b> Choose your performing unbowed Personality and target an enemy Personality with an equal or lower Gold Cost: Bow him. You may move him home.'
Gold_and_Steel = Strategy(card_id=2865, title='Gold and Steel', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> If any enemy units are at the current battlefield, choose your performing unbowed Paragon: Move him to the current battlefield. If he moved, you may target and bow an enemy Personality with equal or lower Personal Honor.'
Guided_by_Honor = Strategy(card_id=2919, title='Guided by Honor', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"Before this battle's resolution: Move a unit home from the current battlefield. You may bow it.<br><b>Battle:</b> If there are no Terrains at the current battlefield: Put this card into play there."
Hard_Pressed = Strategy(card_id=2972, title='Hard Pressed', gold_cost=0, focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, ModernEdition])
'<b>Reaction:</b> Before your target Personality enters a duel, bow him and choose your performing unbowed Samurai at the same location: Your Samurai enters the duel instead. Bow him after the duel ends.'
Hes_Mine = Strategy(card_id=3008, title="He's Mine!", gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, ImperialEdition, GoldEdition, JadeEdition, ModernEdition])
'Before this battle resolves: Give each of your Human Personalities and Followers at the current battlefield +1F, and give each Nonhuman Personality and Follower there -1F.<br><b>Battle:</b> If there are no Terrains at the current battlefield: Put this card into play there.'
Heart_of_Rokugan = Strategy(card_id=3016, title='Heart of Rokugan', gold_cost=0, focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, GoldEdition, DiamondEdition, ModernEdition])
'<b>Battle:</b> Even if you control no units at the current battlefield: Each player targets an unbowed Personality he controls there, if possible. Bow all targets.'
Heavily_Engaged = Strategy(card_id=3037, title='Heavily Engaged', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, ModernEdition])
'<b>Battle:</b> If you control no Personalities <i>(in play)</i>, target one or two Personalities at any location: Bow them. Negate their straightening.<br><b>Reaction:</b> After engaging, if any enemy units are at the current battlefield, choose your performing Personality: Move him there. Straighten him if he moved.'
Hidden_Defenses = Strategy(card_id=3254, title='Hidden Defenses', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Reaction:</b> After another player's action targets your performing Kensai, bow or destroy one of his Weapons: Negate his destruction from the action's effects.<br><b>Battle:</b> Bow your performing Kensai or one of his Weapons: Draw two cards."
HundredFold_Cut = Strategy(card_id=3513, title='Hundred-Fold Cut', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open:</b> Choose your performing Berserker: Straighten him.<br><b>Battle:</b> Choose your performing unbowed Berserker and target an enemy Personality or Follower with lower Force: Bow it.'
Immovable_Object = Strategy(card_id=3671, title='Immovable Object', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open:</b> Choose your performing Samurai: Straighten him and give him +3F. Destroy him before this turn ends.'
In_the_Heart_of_Battle = Strategy(card_id=3725, title='In the Heart of Battle', gold_cost=0, focus_value=3, keywords=[BushidoVirtue, Duty], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Move home a target defending Personality.'
Incapacitated = Strategy(card_id=3730, title='Incapacitated', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, CelestialEdition, ModernEdition])
'<b>Political Battle:</b> Target your Courtier at any location. Bow a target enemy card without attachments. A target player gains or loses 2 Honor.'
Inexplicable_Challenge = Strategy(card_id=3743, title='Inexplicable Challenge', gold_cost=0, focus_value=2, keywords=[Political], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
'<b>Battle/Open:</b> Give your target Personality +2F or you may, if he is a Yojimbo, give him a Force bonus equal to the highest Chi among all Courtiers and Shugenja you control <i>(at any location)</i>.'
Inspired_Devotion = Strategy(card_id=3774, title='Inspired Devotion', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, CelestialEdition, ModernEdition])
'<b>Reaction:</b> After one of your Rings enters play: Search your Fate deck for a card. Put it in your hand.'
Introspection = Strategy(card_id=3793, title='Introspection', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, GoldEdition, DiamondEdition, ModernEdition])
'<b>Ninja Battle:</b> Move home your target Ninja Personality and a target enemy Personality; these movements will not be negated. Bow them.'
Knife_in_the_Darkness = Strategy(card_id=4480, title='Knife in the Darkness', focus_value=3, traits=[], abilities=[], legality=[TwentyFestivalsEdition, EmperorEdition, LotusEdition, CelestialEdition, OnyxEdition, SamuraiEdition, DiamondEdition, ModernEdition])
'<b>Open:</b> Bow your performing Monk and remove this card from the game: Search your Fate deck for a Kiho Battle Strategy, show it, and put it in your hand.'
Martial_Instruction = Strategy(card_id=4843, title='Martial Instruction', gold_cost=0, focus_value=2, keywords=[Kiho], traits=[], abilities=[], legality=[EmperorEdition, DiamondEdition, ModernEdition])
'<b>Reaction:</b> After the resolution of an action from one of your Rings: Search your Dynasty deck for an Event. Remove it, show it, and, after shuffling, put it on top of the deck.<br><b>Open:</b> Bow your target Ring: Draw two cards.'
Meeting_the_Keepers = Strategy(card_id=5018, title='Meeting the Keepers', gold_cost=0, focus_value=4, keywords=[Void], traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, DiamondEdition, ModernEdition])
'<b>Battle/Open:</b> Choose your performing Paragon: Give him +1F for each of his keywords except "Soul of" keywords. Lose 4 Honor.'
Murderous_Intent = Strategy(card_id=5444, title='Murderous Intent', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Samurai and target an enemy Personality with equal or lower Personal Honor: The enemy leader chooses to either bow him or move him home. Gain 2 Honor.'
My_Enemys_Mercy = Strategy(card_id=5457, title="My Enemy's Mercy", gold_cost=0, focus_value=3, keywords=[BushidoVirtue, Compassion], traits=[], abilities=[], legality=[EmperorEdition, SamuraiEdition, ModernEdition])
'<b>Limited:</b> Each player targets a unit he controls with the lowest total Gold Cost of all units he controls, if possible. Destroy all targets. Remove this card from the game. Lose 4 Honor.'
Mysterious_Deaths = Strategy(card_id=5468, title='Mysterious Deaths', gold_cost=6, focus_value=1, keywords=[Unique, Kolat], traits=[], abilities=[], legality=[EmperorEdition, SamuraiEdition, ModernEdition])
'<b>Battle:</b> Bow your performing Monk and target an enemy Personality with equal or lower Chi: Reduce his Force and the Force of each of his Followers to 0. Cards in that unit may not perform actions until this battle ends.'
Nerve_Strike = Strategy(card_id=5532, title='Nerve Strike', gold_cost=0, focus_value=3, keywords=[Kiho], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> After an action on a Strategy is announced, bow your performing Ninja Personality at the current battlefield: Negate the action's effects. Lose 2 Honor."
Ninja_Tricks = Strategy(card_id=5585, title='Ninja Tricks', gold_cost=1, focus_value=1, keywords=[Ninja], traits=[], abilities=[], legality=[EmperorEdition, JadeEdition, ModernEdition])
"<b>Reaction:</b> After you announce an action with a Ranged Attack: Give one Ranged Attack from the action -1 strength. That Ranged Attack may target a card in the Defender's home <i>(if otherwise legal)</i>."
No_Hiding_Place = Strategy(card_id=5599, title='No Hiding Place', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, GoldEdition, SamuraiEdition, DiamondEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Nonhuman Shadowlands Personality and target an enemy Personality: Bow him.'
Ogre_Savagery = Strategy(card_id=5681, title='Ogre Savagery', gold_cost=0, focus_value=0, keywords=[Fear], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Commander and target another Personality in his army: Move the target to a battlefield.'
Opportunistic_Advance = Strategy(card_id=5766, title='Opportunistic Advance', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open:</b> Choose your performing dead Henshin and target your Personality: Your Henshin is reborn. Overlay him onto your Personality. Draw a card. You may take an additional action.'
Oyos_Second_Lesson = Strategy(card_id=5853, title="Oyo's Second Lesson", gold_cost=0, focus_value=3, keywords=[Kiho], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Open:</b> Target a Personality: Bow or straighten him.'
Paid_Off = Strategy(card_id=5861, title='Paid Off', gold_cost=4, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Open:</b> At your next opportunity to take an Open action, you may instead take a Limited action.'
Plans_Within_Plans = Strategy(card_id=5984, title='Plans Within Plans', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, ImperialEdition, JadeEdition, DiamondEdition, ModernEdition])
'<b>Limited:</b> Choose your performing Personality: Give him +2F.'
Prepared_for_Death = Strategy(card_id=6051, title='Prepared for Death', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Target an enemy Personality at the current battlefield: His controller chooses either to bow him, or to choose another location and move him there. If the bowing or movement is negated, remove the Personality from the game.'
Preserving_Honor = Strategy(card_id=6060, title='Preserving Honor', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
'<b>Battle:</b> Target a dishonorable Personality: Destroy him.'
Relentless_Conviction = Strategy(card_id=6247, title='Relentless Conviction', gold_cost=0, focus_value=3, keywords=[Unique], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Bow your performing Courtier at any location and target an enemy attacking Personality: His controller may destroy him. If he did not choose this, discard a card at random from his hand, and choose a player, who gains or loses 3 Honor.'
Remember_Your_Ancestors = Strategy(card_id=6253, title='Remember Your Ancestors', gold_cost=0, focus_value=2, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"As a Focus Effect: Raise this card's Focus Value to 5. If your Personality wins this duel, he loses instead <i>(the other Personality still also loses)</i>.<br><b>Battle:</b> Choose your performing opposed Personality: Give him +5F. If the army he is in during this battle's resolution wins, this battle is tied instead. You will not destroy the province in this battle's resolution."
Rend_the_Soul = Strategy(card_id=6260, title='Rend the Soul', gold_cost=0, focus_value=0, traits=[], abilities=[], legality=[EmperorEdition, GoldEdition, DiamondEdition, ModernEdition])
"<b>Reaction:</b> After the end of an Attack Phase in which you were the Defender: Declare an additional Attack Phase against that phase's Attacker, in which neither player may invite allies and you may only assign one Personality. Give the Personality and each Follower in his unit +1F after he assigns."
Retribution = Strategy(card_id=6290, title='Retribution', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, CelestialEdition, GoldEdition, SamuraiEdition, DiamondEdition, ModernEdition])
"<b>Reaction:</b> Before a player gains or loses Honor from an action's effects, bow your performing Courtier: Choose another player. If the Courtier's Chi is higher than or equal to the Honor gain or loss, the chosen player instead of the original player takes the gain or loss."
Rhetoric = Strategy(card_id=6312, title='Rhetoric', gold_cost=0, focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, GoldEdition, DiamondEdition, ModernEdition])
"Before this battle's resolution: You may bow one or two attacking Personalities at the current battlefield.<br><b>Battle:</b> If there are no Terrains at the current battlefield: Put this card into play there."
Rocky_Terrain = Strategy(card_id=6374, title='Rocky Terrain', gold_cost=0, focus_value=4, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Until your next turn begins, before each time a player gains 1 or more Honor, reduce the gain by 1 if it is not during a battle or Attack Phase.<br><b>Battle:</b> If any enemy units are at the current battlefield, choose your performing Personality: Move him there. Straighten him if he moved.'
Rumors_Travel = Strategy(card_id=6406, title='Rumors Travel', gold_cost=0, focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Limited:</b> Destroy your performing unbowed Courtier and target another player's Personality: His controller may destroy the target. If he did not choose this, search your Dynasty deck for a Personality and bring him into play, paying all costs but paying two more Gold. <i>(Discard him if you are unable to play him.)</i>"
Sacrifice_of_Pawns = Strategy(card_id=6439, title='Sacrifice of Pawns', gold_cost=0, focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, DiamondEdition, ModernEdition])
"<b>Iaijutsu Limited:</b> Your target unbowed Personality challenges another player's target Personality who may refuse. If he refuses, dishonor him and gain 2 Honor. Destroy the duel's loser."
Sanctioned_Duel = Strategy(card_id=6465, title='Sanctioned Duel', gold_cost=0, focus_value=3, keywords=[Iaijutsu], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Yojimbo Personality and target an enemy Personality: Move him home. Bow him if you control a Courtier or Shugenja.<br><b>Battle:</b> Destroy your performing Yojimbo and target one or more of your Courtier or Shugenja Personalities: Move them home.'
Selfless_Defense = Strategy(card_id=6584, title='Selfless Defense', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Open:</b> Bow one or more of your performing Shadowlands Ninja Personalities and target a card without attachments: If the card is an attachment, destroy it. If it is a Personality with Chi lower than or equal to the number of performers, permanently give him <b>Ninja </b>and<b> Shadowlands </b>and take control of him. Lose 3 Honor.'
Shadows_Walk = Strategy(card_id=6676, title='Shadows Walk', gold_cost=4, focus_value=1, keywords=[Fear, Ninja], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> Even if you control no units at the current battlefield, target a Personality: Negate all current and new Force bonuses and penalties on him from actions.'
Shameful_Injury = Strategy(card_id=6698, title='Shameful Injury', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
"<b>Reaction:</b> After another player's Battle action targets your Tattooed Personality, move him to an adjacent battlefield. If he is no longer a legal target for that action, negate its effects."
Snake_Tattoo = Strategy(card_id=7310, title='Snake Tattoo', gold_cost=0, focus_value=2, keywords=[Tattoo], traits=[], abilities=[], legality=[EmperorEdition, GoldEdition, DiamondEdition, ModernEdition])
'<b>Engage:</b> The Attacker has the first opportunity to take a Battle action or pass in this battle.'
Sneak_Attack = Strategy(card_id=7311, title='Sneak Attack', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, LotusEdition, ImperialEdition, CelestialEdition, GoldEdition, JadeEdition, SamuraiEdition, DiamondEdition, ModernEdition])
'<b>Reaction:</b> After a Ranged Attack is targeted: Give it a strength bonus equal to its current strength.'
Sniping = Strategy(card_id=7312, title='Sniping', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, JadeEdition, ModernEdition])
"<b>Favor Political Reaction:</b> Before the resolution of another player's action, you may discard the Imperial Favor. If this discarded it or you control a Personality with 5 or higher Force, negate any Honor losses from the action's effects.<br><b>Battle:</b> Move home a target Personality without attachments."
Solid_Defense = Strategy(card_id=7329, title='Solid Defense', gold_cost=0, focus_value=3, keywords=[Favor, Political], traits=[], abilities=[], legality=[EmperorEdition, SamuraiEdition, ModernEdition])
'<b>Battle:</b> Target your unbowed Samurai with 3 or higher Personal Honor. Permanently give him <b><b>Shadowlands &#149; Undead</b></b>. Move home a target enemy Personality.'
Souls_Sacrifice = Strategy(card_id=7385, title="Soul's Sacrifice", gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, LotusEdition, JadeEdition, DiamondEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Monk: Straighten him. You may take an additional Battle action, which he must perform.'
Spinning_Heel_Kick = Strategy(card_id=7413, title='Spinning Heel Kick', gold_cost=0, focus_value=4, keywords=[Air, Kiho], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Kensai and target an enemy card without attached Weapons or Armor: Bow it. You may attach a Weapon to your Kensai from your hand, paying all costs but paying 4 less Gold if he is defending.'
Stay_Put = Strategy(card_id=7474, title='Stay Put', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Choose your performing unbowed Personality and target an enemy Personality: Your performer duels the target. Destroy the duel's loser."
Steel_on_Steel = Strategy(card_id=7483, title='Steel on Steel', gold_cost=0, focus_value=3, keywords=[Iaijutsu], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, DiamondEdition, ModernEdition])
'<b>Battle:</b> Bow your performing Scout Personality: Ranged 6 Attack, which may target a Personality with attached Followers if you have Reconnaissance.'
Strategic_Strike = Strategy(card_id=7525, title='Strategic Strike', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Choose your performing Paragon and target an enemy Personality: Reduce his Force by an amount equal to your Paragon's Force. You may target and destroy one of the Personality's attachments. Lose 3 Honor."
Strength_in_Terror = Strategy(card_id=7538, title='Strength in Terror', gold_cost=0, focus_value=1, keywords=[Fear], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Personality with 3 or higher Personal Honor: Give him +3F.'
Strength_of_Purity = Strategy(card_id=7546, title='Strength of Purity', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, ImperialEdition, GoldEdition, JadeEdition, DiamondEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Courtier at any location and target an attacking Personality: Move him home. If he moved, bow him. If he is dishonorable, his controller loses Honor equal to his base Personal Honor.'
Summoned_to_Justice = Strategy(card_id=7639, title='Summoned to Justice', gold_cost=0, focus_value=4, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, SamuraiEdition, ModernEdition])
"As a Focus Effect: You may destroy an attachment at the current battlefield if your Personality in this duel is there.<br><b>Battle:</b> Choose your performing unbowed Duelist and target an enemy unit: Bow each Follower and Personality in it with equal or lower Force than your Duelist's Chi."
Superior_Opponent = Strategy(card_id=7654, title='Superior Opponent', gold_cost=0, focus_value=4, keywords=[Fear, Iaijutsu], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Choose one or more of your performing Nonhuman Personalities at the current battlefield and target one of the enemy leader's Personalities there or at home: Create a battlefield <i>(not associated with any province)</i>. Move all the performers and targets there."
Surprise_Attack = Strategy(card_id=7665, title='Surprise Attack', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, SamuraiEdition, ModernEdition])
'<b>Limited:</b> Gain 1 Honor.'
Tell_the_Tale = Strategy(card_id=7862, title='Tell the Tale', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, ImperialEdition, ModernEdition])
'As a Focus Effect: You may choose <i>(now)</i> to delay the effects of losing this duel until after the next Dynasty Phase begins.<br><b>Battle/Open:</b> Choose your performing unbowed Unicorn Clan Personality and target another unit: Straighten it. Gain 1 Honor, or 2 Honor if you do not control the target.'
The_Compassion_of_the_Unicorn = Strategy(card_id=7991, title='The Compassion of the Unicorn', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'As a Focus Effect: You may choose <i>(now)</i> to delay the effects of losing this duel until after the next Dynasty Phase begins.<br><b>Battle:</b> If any enemy units are at the current battlefield, choose your performing unbowed Mantis Clan Personality: Move him there. You may take an additional Battle action.'
The_Courage_of_the_Mantis = Strategy(card_id=7995, title='The Courage of the Mantis', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'As a Focus Effect: After this duel ends, if you won it, give all your provinces +2 strength.<br><b>Open:</b> Choose your performing unbowed Crane Clan Personality: Choose another player. He may draw a card. Draw two cards.'
The_Courtesy_of_the_Crane = Strategy(card_id=7996, title='The Courtesy of the Crane', gold_cost=0, focus_value=4, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Reaction:</b> After the resolution of an action or battle that destroyed any of your Personalities in a defending army, bow your performing Courtier or Empress and target your non-Unique Personality with your Clan alignment in your discard pile: Bring him into play <i>(in your home)</i>, ignoring costs. Gain 2 Honor.'
The_Empress_Address = Strategy(card_id=8059, title="The Empress' Address", gold_cost=0, focus_value=2, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, SamuraiEdition, ModernEdition])
'<b>Battle/Open:</b> You may use each ability on your Stronghold a second time this turn.'
The_Fires_of_War = Strategy(card_id=8084, title='The Fires of War', gold_cost=0, focus_value=4, keywords=[Unique], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> Before the resolution of another player's action, choose your performing Personality: Negate his movement from the action's effects.<br><b>Battle:</b> Choose your performing Personality: Give him and each of his Followers +1F."
The_Height_of_Courage = Strategy(card_id=8126, title='The Height of Courage', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'As a Focus Effect: You may choose <i>(now)</i> to delay the effects of losing this duel until after the next Dynasty Phase begins.<br><b>Battle/Open:</b> If you are a Phoenix Clan player, choose your performing unbowed Phoenix Clan Personality: Name a card. After the next resolution this turn of your action from another Strategy or Ring with that title, draw a card, and choose a player, who discards a card. Remove this card from the game.'
The_Honesty_of_the_Phoenix = Strategy(card_id=8137, title='The Honesty of the Phoenix', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'As a Focus Effect: You may choose <i>(now)</i> to delay the effects of losing this duel until after the next Dynasty Phase begins.<br><b>Battle/Open:</b> Choose your performing unbowed honorable Lion Clan Personality: Permanently give him a bonus raising his PH to 4 and the ability, "<b>Battle:</b> Target an enemy Personality with equal or lower Personal Honor: Bow him. Gain 2 Honor."'
The_Honor_of_the_Lion = Strategy(card_id=8138, title='The Honor of the Lion', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'After the first time, while this card remains in play, that a player passes instead of announcing a Battle action: He chooses and destroys one of his Personalities at the current battlefield.<br><b>Battle:</b> If there are no Terrains at the current battlefield: Put this card into play there.'
The_Killing_Grounds = Strategy(card_id=8188, title='The Killing Grounds', gold_cost=0, focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Courtier or Magistrate and target a Personality: Move him home. If this did not move him home, destroy him.'
The_Laws_Strength = Strategy(card_id=8194, title="The Law's Strength", gold_cost=0, focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> If any enemy units are at the current battlefield, choose your performing Magistrate Personality at home: Move him to the current battlefield. If he moved, straighten his unit. If any dishonorable Personalities are now opposing him, you may take an additional Battle action.'
The_Light_of_Justice = Strategy(card_id=8199, title='The Light of Justice', gold_cost=0, focus_value=4, keywords=[Imperial, Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"As a Focus Effect: You may choose <i>(now)</i> to delay the effects of losing this duel until after the next Dynasty Phase begins.<br><b>Reaction:</b> After an action targets your Scorpion Clan Personality, destroy your performing Scorpion Clan Personality: Negate either the bowing, movement, or destruction of the target from the action's effects."
The_Loyalty_of_the_Scorpion = Strategy(card_id=8207, title='The Loyalty of the Scorpion', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Battle/Open:</b> Choose your performing Commander: Straighten his unit.<br><b>Battle:</b> Choose your performing unbowed Commander and target one or two enemy units with a combined total Gold Cost equal to or lower than your Commander's unit's total Gold Cost: Bow the targets."
The_Power_of_One = Strategy(card_id=8265, title='The Power of One', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Reaction:</b> After another player's Battle action targets your Courtier: The player may choose to lose 3 Honor. If he did not choose this, negate the action's effects.<br><b>Battle:</b> Target one to three enemy dishonorable Personalities: The shadow of their shame shall fall upon their shoulders. Move them home."
The_Power_of_a_Word = Strategy(card_id=8262, title='The Power of a Word', gold_cost=0, focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Battle:</b> Choose your performing Monk and target an enemy Personality whose unit has lower total Force than your Monk's unit: Move the target home. Your Monk feigns his injuries. He contributes Force to his army even if bowed. Lose 3 Honor."
The_Serpents_Deception = Strategy(card_id=8311, title="The Serpent's Deception", gold_cost=0, focus_value=1, keywords=[Fear, Kiho], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Choose your performing defending Courtier and target an enemy Personality: Bow him. After the next time this turn another player's action or a battle resolution destroys your Courtier, draw a card, and choose a player, who gains or loses 2 Honor."
The_Shadow_Court = Strategy(card_id=8313, title='The Shadow Court', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'As a Focus Effect: After this duel ends, if you won it, give all your provinces +2 strength.<br><b>Battle/Open:</b> If you are a Dragon Clan player, choose your performing unbowed Dragon Clan Personality: Name a number. After the next resolution this turn of your action from another Strategy or Ring with a base Focus Value equal to the number, draw a card, and choose a player, who discards a card. Remove this card from the game.'
The_Sincerity_of_the_Dragon = Strategy(card_id=8338, title='The Sincerity of the Dragon', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'As a Focus Effect: After this duel ends, give its winner +3F. <br><b>Battle:</b> Target an opposed unit: Straighten it.'
The_Slow_Death = Strategy(card_id=8340, title='The Slow Death', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
"As a Focus Effect: You may choose <i>(now)</i> to delay the effects of losing this duel until after the next Dynasty Phase begins.<br><b>Battle:</b> Choose your performing unbowed Spider Clan Personality and target an enemy Personality or Follower: Destroy it if it is bowed. Reduce its Force by an amount equal to your Personality's Force. Bow it if its Force is now 0."
The_Strength_of_the_Spider = Strategy(card_id=8362, title='The Strength of the Spider', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> If you have Reconnaissance, choose your performing unbowed Scout Personality, and target an enemy card: Bow it. Bow its unit if you are a Crane Clan player.'
The_Trap_is_Sprung = Strategy(card_id=8394, title='The Trap is Sprung!', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Reaction:</b> After engaging, choose your performing Scout at the current battlefield: You have Reconnaissance there. Negate the next card effect that bows one or more of your Personalities who is there <i>(at the time)</i>.'
Torchs_Flame_Flickers = Strategy(card_id=8639, title="Torch's Flame Flickers", gold_cost=0, focus_value=1, keywords=[Recon], traits=[], abilities=[], legality=[EmperorEdition, SamuraiEdition, ModernEdition])
"<b>Battle:</b> Move home a target Personality whose unit's total Force is 7 or higher."
Treachery_and_Deceit = Strategy(card_id=8741, title='Treachery and Deceit', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, LotusEdition, JadeEdition, DiamondEdition, ModernEdition])
'<b>Reaction:</b> Before your Dynasty Phase ends: Take an additional Limited or Open action.'
Twist_of_Fate = Strategy(card_id=8917, title='Twist of Fate', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, ImperialEdition, ModernEdition])
"<b>Reaction:</b> After another player's action targets your Oni: Negate its effects."
Undetectable_Enemy = Strategy(card_id=8961, title='Undetectable Enemy', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Reaction:</b> Before the resolution of another player's action: Reduce each Honor loss from its effects by 3 <i>(minimum 0)</i>. You may target and rehonor a dishonorable Personality.<br><b>Battle:</b> Bow your performing Shugenja and target an enemy card: Bow it. Gain 2 Honor."
Unimpeachable_Name = Strategy(card_id=8989, title='Unimpeachable Name', gold_cost=0, focus_value=1, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Bow your performing Ninja: Ranged 3 Attack. If the Ranged Attack targeted a Personality, you may compare it against his Chi.'
Unseen_Assailant = Strategy(card_id=9011, title='Unseen Assailant', gold_cost=0, focus_value=2, keywords=[Ninja], traits=[], abilities=[], legality=[EmperorEdition, SamuraiEdition, ModernEdition])
"<b>Open:</b> Bow your performing Courtier and target one or more Personalities, up to an amount equal to your Courtier's Chi: Give <b>Cavalry</b> to them and to each of their Followers."
Useful_Connections = Strategy(card_id=9046, title='Useful Connections', gold_cost=0, focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Open:</b> Choose your performing unbowed Courtier and target a dishonorable Personality: His controller loses 2 Honor. After each time he is assigned <i>(this turn)</i>, his controller loses 1 Honor.'
Veiled_Menace = Strategy(card_id=9130, title='Veiled Menace', gold_cost=0, focus_value=2, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, SamuraiEdition, ModernEdition])
"<b>Dark Virtue Open:</b> Target your unbowed Samurai. Give a target Personality a Force penalty equal to your Samurai's Force."
Vigilant_Eyes = Strategy(card_id=9156, title='Vigilant Eyes', gold_cost=0, focus_value=4, keywords=[DarkVirtue, Insight], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Move your performing opposed Personality home: Increase or decrease the strength of the current battlefield's province by an amount equal to the number of units on the enemy side there. Gain 2 Honor."
Wall_of_Honor = Strategy(card_id=9198, title='Wall of Honor', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> If you control a Terrain, target a card in a unit: Bow or straighten the target.'
Well_Prepared = Strategy(card_id=9287, title='Well Prepared', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, LotusEdition, GoldEdition, SamuraiEdition, DiamondEdition, ModernEdition])
'While at the current battlefield, each of your Tacticians has the ability, "<b>Tactical Reaction:</b> Before this battle\'s resolution: Give this Tactician a Force bonus equal to his Chi."<br><b>Battle:</b> If there are no Terrains at the current battlefield: Put this card into play there.'
White_Shore_Plain = Strategy(card_id=9323, title='White Shore Plain', gold_cost=0, focus_value=3, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, GoldEdition, JadeEdition, DiamondEdition, ModernEdition])
"You may only play one copy of Words Have Strength in reaction to any one resolution.<br><b>Reaction:</b> After a battle's resolution, or the resolution of another player's Battle action, if the resolution or action destroyed any of your Courtiers or Magistrates: Choose a player, who loses 3 Honor."
Words_Have_Strength = Strategy(card_id=9377, title='Words Have Strength', gold_cost=0, focus_value=2, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])