from __future__ import annotations
from .common import Strategy
from l5r_auto.keywords import Courage, Forest, Honor, Kata, Kharmic, Terrain
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition
'<b>Kiho Battle/Open:</b> Bow your target unbowed Monk or Shugenja. Search your Fate discard pile, then deck, for a Ring. Show it and put it in your hand.'
Aligned_with_Fire = Strategy(card_id=12534, title='Aligned with Fire', focus_value=1, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"Your Ranged Attacks have +1 strength. Other players' Ranged Attacks have -1 strength.<br><b>Battle/Engage:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play."
Archers_Position = Strategy(card_id=12535, title="Archer's Position", focus_value=3, keywords=[Terrain], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"<b>Invest :g2::</b> The winner also destroys a card without attachments in the loser's unit, and gains 1 Honor if this destroyed an attachment.<br><b>Iaijutsu Battle:</b> Your target unbowed Personality challenges a target enemy Personality. Bow the loser."
Avenge_Your_Slights = Strategy(card_id=12536, title='Avenge Your Slights', focus_value=3, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard an Honor card to give an Honor gain or loss +1 or -1.)</i><br>Discipline :g3: or :g0: if you are the Defender. <br><b>Battle:</b> If there are enemy units at this battlefield, move your target Personality there from home. If the target moved to defend, straighten him or her.'
Battlefield_Defamation = Strategy(card_id=12537, title='Battlefield Defamation', focus_value=3, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Assassin Open, :g10::</b> Destroy a target Personality with 3 or lower Chi. Lose Honor equal to half your Starting Family Honor, rounded up.'
Betrayed_from_Within = Strategy(card_id=12538, title='Betrayed from Within', focus_value=2, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Battle/Open:</b> A target player may only put one more Ring into play this turn. <br><b>Battle:</b> Melee 3 Attack, which may not target a Defending Personality. Give your target Personality Resilient. <i>(Once per game per card, a Resilient card does not die in battle resolution.)</i>'
Cleaving_the_Wave = Strategy(card_id=12539, title='Cleaving the Wave', focus_value=1, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard an Honor card to give an Honor gain or loss +1 or -1.)</i><br><b>Battle:</b> Straighten your target opposed card.'
Die_on_Your_Feet = Strategy(card_id=12540, title='Die on Your Feet', focus_value=4, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"<b>Battle:</b> Target your unbowed Personality. Reduce a target enemy Follower's or Personality's Force by your Personality's Personal Honor. If that Personal Honor is 4 or more, Ranged 0 Attack against the enemy target <i>(if legal)</i>."
Disciplined_Advance = Strategy(card_id=12541, title='Disciplined Advance', focus_value=2, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'At this battlefield, Personalities without attachments have -1F, and your Shugenja with Spells have +1F/+1C.<br><b>Battle:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play.'
Duel_of_Shugenja = Strategy(card_id=12542, title='Duel of Shugenja', focus_value=2, keywords=[Terrain], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"Disciplne :g3:.<br><b>Battle:</b> Dishonor a target enemy Personality.<br><b>Battle:</b> Fear 3 that may target Items. After this bows a card in a dishonorable Personality's unit, destroy that card."
Ending_the_Chase = Strategy(card_id=12543, title='Ending the Chase', focus_value=2, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"This card's Interrupt ability costs :g0: if it Interrupts the Tactical Advantage ability.<br><b>Open:</b> Put this Kata into play. Discard your other Kata in play.<br><b>Interrupt, :bow:, :g1::</b> After the Battle action discards a card from your hand, draw a card."
Endless_Drills = Strategy(card_id=12544, title='Endless Drills', focus_value=4, keywords=[Kharmic, Kata], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'Compassion: Discipline :g2:. <i>(Compassion takes effect while you have fewer Provinces than anyone else. Pay 2 Gold to play, then remove from the game, this Discipline in your discard.)</i><br><b>Battle:</b> Move home your target Personality, who must be opposed if defending. As the target moves, straighten his or her unit and draw a card.'
Evasion = Strategy(card_id=12545, title='Evasion', focus_value=4, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard a Courage card to give a Fear effect +2 or -2 strength or discard an Honor card to give an Honor gain or loss +1 or -1.)</i> <br>This card has +2FV during a duel in which you were challenged, or during an action that discarded it from your hand.'
Fight_on_Your_Back = Strategy(card_id=12546, title='Fight on Your Back', focus_value=3, keywords=[Courage, Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Battle, :g*::</b> Target your unbowed Personality. If the target is Kensai, you may Equip a target Weapon from your discard pile to him or her. You may target and move home an enemy Personality with fewer Weapons.'
Fighting_Unrestrained = Strategy(card_id=12547, title='Fighting Unrestrained', focus_value=1, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"<b>Battle:</b> Target your unbowed Personality. Fear equal to his or her Chi that may target Items and Spells. If your Personality is a Magistrate and the Personality in the enemy target's unit is dishonorable or Shadowlands, the Fear destroys cards after bowing them. Bow your Personality if this destroyed a Personality."
Illegal_Justice = Strategy(card_id=12548, title='Illegal Justice', focus_value=1, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'As a Focus Effect, before a card is destroyed for losing the duel, bow it instead.<br><b>Battle:</b> Move home a target Personality with no attachments or with three or more attachments.'
Indifference = Strategy(card_id=12549, title='Indifference', focus_value=2, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard a Courage card to give a Fear effect +2 or -2 strength.)</i> <br>After you announce a Courage action, give a target enemy Follower or Personality -2F.<br><b>Battle/Engage:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play.'
Into_the_Shinomen = Strategy(card_id=12550, title='Into the Shinomen', focus_value=1, keywords=[Courage, Forest, Terrain], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard an Honor card to give an Honor gain or loss +1 or -1.)</i><br><b>Battle:</b> Fear equal to the Personal Honor of your target unbowed Personality. After this bows a card in a unit whose Personality has <b>lower</b> Personal Honor, give your Personality +2F.'
Matsu_KiAi = Strategy(card_id=12551, title='Matsu Ki-Ai', focus_value=3, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard an Honor card to give an Honor gain or loss +1 or -1.)</i><br><b>Iaijutsu Battle:</b> Target your unbowed Personality and target an enemy Personality with equal or higher Chi. Bow a card in the enemy unit without attachments, or any card in that unit if your Personality is a Duelist. Gain 1 Honor if you are the Defender.'
My_Steel_is_Stronger = Strategy(card_id=12552, title='My Steel is Stronger', focus_value=4, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Battle:</b> Fear 3. If one of your Magistrates has been destroyed this battle, the Fear has +1 strength and may target a Personality with attached Followers.'
Mysterious_Murder = Strategy(card_id=12553, title='Mysterious Murder', focus_value=3, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"<b>Battle:</b> Bow your target unbowed Follower. Target a Battle Strategy in your discard pile with a lower Focus Value than your Follower's Force, and put it into your hand. Take an additional action if your Follower is attached to a Commander."
Necessary_Sacrifice = Strategy(card_id=12554, title='Necessary Sacrifice', focus_value=4, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"This card's ability costs 1 less Gold for each of your Ninja at this battlefield with non-zero Gold Cost.<br><b>Ninja Battle, :g4::</b> If they would be opposed, create two 2F/2C/0PH Ninja Personalities with your Clan Alignment, and with Shadowlands if you are Spider Clan. Lose 3 Honor. Remove them from the game before the turn ends."
Ninja_Training_Exercise = Strategy(card_id=12555, title='Ninja Training Exercise', focus_value=3, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"<b>Open:</b> Put this Kata into play. Discard your other Kata in play without this card's title.<br><b>Open, :bow:, :g3::</b> Put your target Ring from your hand into play; while it remains in play, it does not count towards an Enlightenment Victory. Put it into your hand after your next turn begins."
Opening_the_Hearts_Door = Strategy(card_id=12556, title="Opening the Heart's Door", focus_value=3, keywords=[Kata], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard an Honor card to give an Honor gain or loss +1 or -1.)</i><br>Your Personalities have +1F for each bowed card type in units opposing them.<br><b>Battle:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play.'
Phalanx_Formation = Strategy(card_id=12557, title='Phalanx Formation', focus_value=3, keywords=[Honor, Terrain], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard an Honor card to give an Honor gain or loss +1 or -1.)</i><br><b>Siege Open:</b> If you control at least three Personalities, straighten one or two of your target Fortifications. If this straightened two Fortifications, they will not produce Gold this turn.'
Repairing_the_Walls = Strategy(card_id=12558, title='Repairing the Walls', focus_value=3, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<i>(Repeatable Interrupt: Discard an Honor card to give an Honor gain or loss +1 or -1.)</i> <br>Courtesy: The Force penalty is increased by 1. <i>(Courtesy does not take effect if you went first. Absent actions may be taken without presence.)</i><br><b>Battle:</b> Give a target enemy Personality a Force penalty equal to his or her Chi.'
Retracing_Steps = Strategy(card_id=12559, title='Retracing Steps', focus_value=2, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Open:</b> Target your Personality with exactly one Weapon. Permanently give him or her the trait, "May not attach more than one Weapon," and permanently give the Weapon the ability, "<b>Battle, :bow::</b> Melee 3 Attack. If this Weapon is attached to a Kensai, straighten it."'
Scorpion_Flexibility = Strategy(card_id=12560, title='Scorpion Flexibility', focus_value=1, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'Discipline :g2:. <i>(Pay 2 Gold to play, then remove from the game, this Discipline in your discard.)</i><br><b>Battle:</b> Give this Province +3 strength. Personalities may not enter play this battle.'
Secretive_Defense = Strategy(card_id=12561, title='Secretive Defense', focus_value=4, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"<b>Ninja Open:</b> Target your unbowed Ninja Personality and another Personality with a Poison token or without abilities. Your Ninja copies the Personality's printed Force, Chi, and abilities that do not copy abilities. Lose 1 Honor."
Stealing_the_Scrolls = Strategy(card_id=12562, title='Stealing the Scrolls', focus_value=4, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Battle:</b> Bow your target unbowed Follower. Destroy a target enemy attachment with equal or lower Force. If your Follower is attached to a Commander, you may either straighten the Follower, or target and bow an attachment in the same enemy unit with equal or lower Force than your Follower.'
Superior_Assault = Strategy(card_id=12563, title='Superior Assault', focus_value=1, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Battle:</b> Destroy your target Fortification at the current battlefield to move home a target enemy Personality. Bow his unit as he moves. Gain 1 Honor.'
The_Fall_of_Kyuden_Bayushi = Strategy(card_id=12564, title='The Fall of Kyuden Bayushi', focus_value=3, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"As a Focus Effect, give this card +1FV if it was the last card you focused in the duel.<br><b>Iaijutsu Battle:</b> Your target unbowed Personality challenges another player's target Personality. Give the winner +3F."
The_Last_Strike = Strategy(card_id=12565, title='The Last Strike', focus_value=4, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Invest :g2::</b> If the target is Void, draw a card. <i>(Upon being played, permanently increase the Gold Cost by the Invest cost to get the effect.)</i><br><b>Void Kiho Battle/Open:</b> Target your unbowed Monk or Shugenja. Search your Fate deck for a card, set it aside face-down, and put it on top of the deck after shuffling.'
The_Search_for_Enlightenment = Strategy(card_id=12566, title='The Search for Enlightenment', focus_value=1, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"<b>Interrupt:</b> If another player has resolved two or more actions this turn that reduced any of your Human cards' Force, negate all future Force penalties <i>(including any this is Interrupting)</i> to your Human cards from that player's actions until this battle ends."
Unbreakable_Courage = Strategy(card_id=12567, title='Unbreakable Courage', focus_value=4, keywords=[Courage, Kharmic], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"Discipline :g2:.<br><b>Political Open:</b> Bow your target unbowed Courtier. Reduce a target Personality's Force by your Courtier's Chi. If the Personality is dishonorable, his or her controller loses 1 Honor."
Unforgivable_Shame = Strategy(card_id=12568, title='Unforgivable Shame', focus_value=2, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'Compassion: The Melee Attack has +2 strength. <i>(Compassion takes effect while you have fewer Provinces than anyone else.)</i><br><b>Battle:</b> Melee 1 Attack that may target Items and Spells and has +2 strength if the target is an attachment.'
Unguarded_Attack = Strategy(card_id=12569, title='Unguarded Attack', focus_value=3, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Battle:</b> Fear 3. After this bows the target, destroy it if it has 2 or lower Force. <i>(Bow a target enemy Follower or Personality without Followers with 3 or lower Force)</i> Lose 2 Honor.'
Unshackled = Strategy(card_id=12570, title='Unshackled', focus_value=1, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"You must discard the Imperial Favor and give this Strategy's ability Favor Political to play it using Discipline. <br>Discipline :g0:. <br><b>Battle/Open:</b> Bow your target unbowed Ring. Straighten one or two of your target cards in units."
Walking_with_the_Air = Strategy(card_id=12571, title='Walking with the Air', focus_value=3, keywords=[Kharmic], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Open:</b> Put this Kata into play. Discard your other Kata in play.<br><b>Open, :bow::</b> Put the top card of your Fate deck under this Kata <i>(face-down but you may look at it)</i>.<br><b>Open, :bow:, :g3::</b> Put a card underneath this Kata into your hand.'
Wisdoms_Burden = Strategy(card_id=12572, title="Wisdom's Burden", focus_value=4, keywords=[Kata], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'This action costs 3 less Gold if you have <b>Courtesy </b>or if it only targets one attachment.<br><b>Battle, :g*::</b> Destroy one or two target enemy attachments with total Gold Cost equal to the amount paid; if you target two attachments they must be in the same unit, which must have at least three attachments.'
Without_Your_Weapons = Strategy(card_id=12573, title='Without Your Weapons', focus_value=2, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
"You must discard the Imperial Favor and give this Strategy's ability Favor Political to play it using Discipline. <br>Discipline :g0:. <br><b>Political Battle:</b> Fear equal to your target Courtier's Chi. A target player gains or loses 1 Honor."
Word_from_the_Imperial_Court = Strategy(card_id=12574, title='Word from the Imperial Court', focus_value=4, keywords=[Honor], traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])
'<b>Open:</b> Target your Human non-Shadowlands Personality. You reveal the corruption within. Permanently give the target Shadowlands and the ability, "<b>Battle:</b> Fear 4," and give him or her a +1F token. Lose 3 Honor.'
Your_True_Colors = Strategy(card_id=12575, title='Your True Colors', focus_value=4, traits=[], abilities=[], legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition])