from __future__ import annotations
from .common import Strategy
from l5r_auto.keywords import BushidoVirtue, Compassion, DarkVirtue, Favor, Fear, Iaijutsu, Imperial, Kiho, Ninja, Pearl, Political, Recon, Siege, Strength, Terrain, Unique
from l5r_auto.legality import CelestialEdition, EmperorEdition, IvoryEdition, ModernEdition
'<b>Limited, :g3::</b> Draw two additional cards before your turn ends.'
A_Game_of_Dice = Strategy(card_id=25, title='A Game of Dice', gold_cost=3, focus_value=4, keywords=[Unique], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, CelestialEdition, ModernEdition])
"<b>Open, :gstar::</b> Destroy your target performing Yojimbo to Recruit your target discarded Courtier or Shugenja for less Gold equal to your Yojimbo's printed Gold Cost plus 1.<br><b>Battle/Open:</b> Straighten your target performing Personality. You may take an additional action appropriate to this phase."
A_Yojimbos_Duty = Strategy(card_id=101, title="A Yojimbo's Duty", focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Favor Imperial Political Open:</b> Target your performing unbowed Courtier and discard the Imperial Favor to dishonor a target Personality. His controller may not assign him, and he will not move, to battlefields this turn.'
Accidental_Confession = Strategy(card_id=109, title='Accidental Confession', gold_cost=0, focus_value=3, keywords=[Favor, Imperial, Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Ninja Open:</b> Bow your target performing Ninja Personality to destroy a target Retainer.<br><b>Ninja Battle:</b> Target your performing Ninja Personality with no non-Ninja Followers at the current battlefield. Move him to a different location. After this moves him, straighten his unit. Discard a card in a Province.'
Asset_Denial = Strategy(card_id=634, title='Asset Denial', gold_cost=0, focus_value=1, keywords=[Ninja], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open, :gstar::</b> Destroy a target attachment with a Gold Cost less than or equal to what you paid for this action minus two.<br><b>Absent Battle:</b> If there are enemy units at the current battlefield, move your target performing Personality at any location there. Straighten him if this moved him.'
Broken_Alliance = Strategy(card_id=1150, title='Broken Alliance', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Open:</b> Straighten your target performing Samurai's unit.<br><b>Battle:</b> Target your performing unbowed Samurai to bow a target an enemy card without attachments. Destroy it if your Samurai is a Paragon."
Cast_Aside_the_Weak = Strategy(card_id=1225, title='Cast Aside the Weak', gold_cost=0, focus_value=4, keywords=[DarkVirtue, Strength], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Open:</b> Target your performing unbowed Tactician to give another of your target Personalities +3F. After the next time this turn another player's action targets him, negate its effects."
Consideration = Strategy(card_id=1461, title='Consideration', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open:</b> Target a Personality. Either negate all current and new Force bonuses and penalties on him from actions, or straighten his unit.'
Creating_Order = Strategy(card_id=1557, title='Creating Order', focus_value=4, keywords=[Unique], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, CelestialEdition, ModernEdition])
"<b>Political Open:</b> Your target performing unbowed Personality challenges another player's target Personality. In this duel, each Personality uses Personal Honor as his or her duel stat. The winner gains 1 Honor. Bow and dishonor the loser."
Duel_of_Haiku = Strategy(card_id=2245, title='Duel of Haiku', gold_cost=0, focus_value=4, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'Other players\' Personalities and Followers in play have -2 Gold Cost and all players have the ability, "<b>Favor Political Limited:</b> Discard the Imperial Favor or pay 6 Gold to discard a card titled Economic Repercussions from play."<br><b>Limited:</b> Put this card into play.'
Economic_Repercussions = Strategy(card_id=2280, title='Economic Repercussions', gold_cost=0, focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Interrupt:</b> Negate a Battle action's effects taken by the Attacker if it is taken before the Defender's first normal opportunity to act or pass.<br><b>Battle:</b> Bow a target enemy card without attachments."
Entrenched_Position = Strategy(card_id=2355, title='Entrenched Position', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, CelestialEdition, ModernEdition])
"As a Focus Effect: After this duel's resolution, its winner's controller discards a card.<br><b>Battle:</b> Choose your performing unbowed Commander and target an enemy Personality: If your Commander has a Follower, you may target and destroy an attachment in the Personality's unit. Move him home."
Feint_Strike = Strategy(card_id=2506, title='Feint & Strike', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Reaction:</b> After engaging, if any enemy units are at the current battlefield: Create a 4F/4C/3PH <b>Imperial &#149; Samurai &#149; Duelist &#149; Magistrate</b> Personality on your side there. Remove him from the game after this battle ends.'
Fruitless_Search = Strategy(card_id=2708, title='Fruitless Search', gold_cost=0, focus_value=4, keywords=[Unique, Imperial, Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Reaction:</b> After engaging, choose your performing Samurai at the current battlefield: Create a 1F <b>Ashigaru &#149; Cavalry</b> Follower and attach it to him. If he is a Paragon, gain 2 Honor and draw a card.'
Grateful_Reward = Strategy(card_id=2895, title='Grateful Reward', gold_cost=0, focus_value=3, keywords=[BushidoVirtue, Compassion], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Personality and target an enemy Personality or Follower: Give it -4F. If your Personality is Nonhuman, give each of your Personalities at the current battlefield +1F.'
Gripped_by_Terror = Strategy(card_id=2908, title='Gripped by Terror', gold_cost=0, focus_value=1, keywords=[Fear], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"Before this battle's resolution: Choose and bow zero to two cards at the current battlefield with 4 or greater Force.<br><b>Battle:</b> If no Terrain is at the current battlefield: Put this card into play there."
Heart_of_Darkness = Strategy(card_id=3013, title='Heart of Darkness', gold_cost=0, focus_value=4, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'As a Focus Effect: Delay all consequences of losing this duel <i>(from any source)</i> until the end of the turn.<br><b>Battle:</b> Choose your performing bowed Personality: Straighten him. If he is Unique, you may take an additional Battle action to use one of his base abilities.'
Honor_Never_Falls = Strategy(card_id=3426, title='Honor Never Falls', gold_cost=0, focus_value=3, keywords=[Unique], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Choose your performing Berserker Personality and target another player's Personality not at the current battlefield: Move them both there. Straighten each unit that this moved."
Intimidation = Strategy(card_id=3790, title='Intimidation', gold_cost=0, focus_value=1, keywords=[Fear], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Even if you control no units at the current battlefield, choose your performing unbowed Kensai, who may be at an adjacent battlefield to the current one if he has a Weapon attached: Ranged 6 Attack <i>(against a target at the current battlefield)</i>.'
Never_Beyond_My_Reach = Strategy(card_id=5533, title='Never Beyond My Reach', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Bow your performing Shugenja, and destroy him unless he is Nonhuman: Ranged Attack with strength equal to his Force plus Chi.<br><b>Battle:</b> Bow your performing Shugenja: Ranged Attack with strength equal to his Force or Chi.'
Pearls_Spirits = Strategy(card_id=5906, title='Pearls & Spirits', gold_cost=0, focus_value=4, keywords=[Pearl], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Limited:</b> Target one or two face-down cards in provinces: Turn them face-up.<br><b>Battle/Open:</b> Target an attachment owned by another player: He may pay 4 Gold. If he did not, return it to its owner's hand."
Petty_Squabbles = Strategy(card_id=5939, title='Petty Squabbles', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Reaction:</b> After a battle ends in which you destroyed a province as the Attacker: Create a Holding with the trait "Bow this card: Produce 3 Gold" <i>(it enters play bowed)</i>. Draw a card.'
Returning_Home = Strategy(card_id=6299, title='Returning Home', gold_cost=2, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Open:</b> If you control two or more Nonhuman Personalities, choose your performing Nonhuman Personality face-up in your province: Bring him into play, paying all costs. Refill the province face-up.'
Rise_of_the_Dark_Naga = Strategy(card_id=6343, title='Rise of the Dark Naga', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> After engaging, choose your performing unbowed Scout at the current battlefield: You have Reconnaissance there. Put a non-Unique Battle Strategy in your discard pile into your hand. After this battle ends, if you did not destroy the battlefield's province or an army, discard a card at random."
Seeking_the_Truth = Strategy(card_id=6566, title='Seeking the Truth', gold_cost=0, focus_value=2, keywords=[Recon], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Ranged 4 Attack.<br><b>Battle:</b> Even if you control no units at the current battlefield: Increase or decrease its province's strength by the number of Castles you control."
Siege_Volley = Strategy(card_id=7248, title='Siege Volley', gold_cost=0, focus_value=3, keywords=[Siege], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Monk: Straighten him. If you control a Temple, you may target a Personality or Follower and bow or straighten it.'
Steadfast_Defense = Strategy(card_id=7477, title='Steadfast Defense', gold_cost=0, focus_value=2, keywords=[Kiho], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Target an enemy Personality: You may target one of his attachments and pay Gold equal to its Gold Cost minus four. If you did, destroy it. Move the Personality home.'
Sundering_Strike = Strategy(card_id=7650, title='Sundering Strike', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Limited:</b> Target another player's Personality: Create a 0F/3C/0PH <b>Assassin &#149; Duelist</b> Personality. He issues an unrefusable challenge to the targeted Personality. Destroy the duel's loser. After the duel ends, remove the created Personality from the game."
Sword_for_Hire = Strategy(card_id=7696, title='Sword for Hire', gold_cost=10, focus_value=4, keywords=[Iaijutsu], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> After the end of an Attack Phase in which you were the Defender: Create an additional Attack Phase with the previous phase's Attacker as the Defender. During this Attack Phase, you will not destroy more than one of the Defender's provinces and your Personalities may not assign and will not move unless they are Paragons or Battle Maidens."
The_Perfect_Moment = Strategy(card_id=8257, title='The Perfect Moment', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Magistrate and target an enemy Personality: Your Magistrate takes him into custody. If he is dishonorable, destroy his attachments. Move him home.'
Wanted_for_Questioning = Strategy(card_id=9208, title='Wanted for Questioning', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])