from __future__ import annotations
from .common import Strategy
from l5r_auto.keywords import BushidoVirtue, Courage, DarkVirtue, Favor, Fear, Fire, Heroic, Iaijutsu, Insight, Kata, Kiho, Ninja, Political, Siege, Tattoo, Terrain, Water
from l5r_auto.legality import CelestialEdition, EmperorEdition, ModernEdition, OnyxEdition, TwentyFestivalsEdition
'<b>Battle:</b> Target your performing unbowed Personality. Bow a target enemy card without attachments and with lower Gold Cost. If your Personality is a Magistrate, you may target an enemy card and reduce its Gold Cost to 0.'
A_Fugitive_Apprehended = Strategy(card_id=24, title='A Fugitive Apprehended', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Open:</b> Target a dishonorable Personality and pay Gold equal to his base Personal Honor plus one: He may not be assigned, and will not move, to battlefields this turn.<br><b>Open:</b> Target a dishonorable Personality: Give him two -2 Gold Cost tokens.'
A_Quiet_Transaction = Strategy(card_id=70, title='A Quiet Transaction', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Target your performing Kensai. Straighten him and all his Weapons. Battle abilities on his Weapons may be used a second time this turn. You may take an additional Battle action.'
Again = Strategy(card_id=127, title='Again!', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"This battlefield's province has a maximum strength equal to its base strength.<br><b>Battle:</b> Destroy all other Terrains at the current battlefield. Put this card into play there."
Ancient_Feud = Strategy(card_id=397, title='Ancient Feud', gold_cost=0, focus_value=3, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Heroic Battle:</b> Target your performing unbowed Hero, who must be the only Personality in his army, to target an enemy Personality and bow his unit.'
Barred_Passage = Strategy(card_id=708, title='Barred Passage', gold_cost=0, focus_value=2, keywords=[Heroic], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Create a <i>(bowed)</i> Holding with the trait "Bow this card: Produce 3 Gold." Negate your Stronghold\'s straightening <i>(this turn)</i>.<br><b>Open:</b> Destroy your target Holding: Create a Samurai Personality with 3C/2PH and Force equal to the Holding\'s base Gold Cost.'
Basic_Lesson = Strategy(card_id=713, title='Basic Lesson', gold_cost=4, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Political Open:</b> Destroy one to three target attachments with a 0 Gold Cost.<br><b>Favor Political Limited:</b> Bow your Stronghold and discard the Imperial Favor to draw two cards.'
Bonds_of_Coin = Strategy(card_id=1092, title='Bonds of Coin', gold_cost=0, focus_value=4, keywords=[Favor, Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Fear Battle:</b> Target your performing unbowed Paragon to bow a target card in an enemy unit. Negate its next straightening <i>(this turn)</i> if your Paragon is Shadowlands. Lose 2 Honor.'
Bow_Before_My_Will = Strategy(card_id=1121, title='Bow Before My Will', gold_cost=0, focus_value=1, keywords=[Fear], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Target an enemy card without attachments: Bow it.<br><b>Battle/Open:</b> Target a Region <i>(at any province)</i> or a Terrain: Destroy it.'
Brawl = Strategy(card_id=1127, title='Brawl', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Destroy your target performing unbowed Samurai to target an enemy card without attachments. Abilities on other cards now in its unit may not be used. Destroy the targeted card.'
Costly_Opportunity = Strategy(card_id=1522, title='Costly Opportunity', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'As a Focus Effect, after this duel ends, if your Personality won it, gain 2 Honor.<br><b>Political Battle/Open:</b> Target your performing unbowed Magistrate to target a Personality. <i>His lord casts him out for treachery.</i> Permanently remove his Clan Alignment keywords. Dishonor him. If he is at a battlefield, bow him and choose a player, who gains or loses 1 Honor.'
Discovering_a_Conspiracy = Strategy(card_id=2011, title='Discovering a Conspiracy', gold_cost=0, focus_value=4, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Target one or more of your performing Tacticians at the same, non-current battlefield to target a Personality opposing them. <i>He is lured into a trap.</i> Move the targets to the current battlefield.'
Dislodge_the_Foe = Strategy(card_id=2024, title='Dislodge the Foe', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Target your performing unbowed Magistrate to target an enemy Personality. If he has no attachments and is dishonorable, Kolat, Ninja, or Shadowlands, destroy him. Move him home.'
Dispensing_Justice = Strategy(card_id=2029, title='Dispensing Justice', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'As a Focus Effect, you may put a non-Unique Strategy with a Political ability in your discard pile into your hand.<br><b>Political Open:</b> Bow your target performing Courtier to give a target Personality -3F. If he is dishonorable, his controller loses Honor equal to his printed Personal Honor.'
Disreputable_Deal = Strategy(card_id=2031, title='Disreputable Deal', gold_cost=0, focus_value=2, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Reaction:</b> Before the resolution of a Battle action that was taken as an additional action, negate its effects.<br><b>Battle:</b> Target your performing unbowed Personality to move home a target Personality without attachments.'
Effortless_Counterattack = Strategy(card_id=2283, title='Effortless Counterattack', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Monk: You may target and destroy an enemy attachment. If your Monk has any Fire tokens, Ranged 4 Attack.'
Engulfing_Flames = Strategy(card_id=2342, title='Engulfing Flames', gold_cost=0, focus_value=1, keywords=[Fire, Kiho], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Destroy your performing Shadowlands Ninja Personality and target a Ninja Personality in your discard pile: Bring him into play at the current battlefield, paying all costs but reducing his Gold cost to enter play by the performer's Gold Cost. Lose 2 Honor. You may take an additional Battle action."
Goju_Plot = Strategy(card_id=2856, title='Goju Plot', gold_cost=0, focus_value=2, keywords=[Ninja], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Destroy your performing unbowed Personality and target an enemy unit with total Force equal to or lower than your performer's Force, plus Personal Honor, plus one if he is defending: Destroy the enemy unit."
Great_Sacrifice = Strategy(card_id=2900, title='Great Sacrifice', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"After each resolution of one of your Battle actions <i>(including this card's)</i>: Give this province +1 strength until this card leaves play.<br><b>Battle:</b> If there is no Terrain in play at the current battlefield: Put this card into play there."
Hasty_Fortifications = Strategy(card_id=2996, title='Hasty Fortifications', gold_cost=0, focus_value=3, keywords=[Siege, Terrain], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Open:</b> Bow your performing Nonhuman: It hibernates. Negate its straightening until your next turn begins. After the next time this game another player's Battle action targets it, negate the action's effects."
Hibernation = Strategy(card_id=3065, title='Hibernation', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Bow your performing Artisan at any location and discard the top card of your Fate deck: Increase the current battlefield's province's strength by the card's Focus Value plus one."
Improved_Defenses = Strategy(card_id=3720, title='Improved Defenses', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Political Open:</b> Choose your performing unbowed Courtier. Take the Imperial Favor.<br><b>Favor Political Battle:</b> Discard the Imperial Favor to target an enemy Personality. Dishonor him. Bow him. Move him home. His controller loses 2 Honor.'
Insulting_Gesture = Strategy(card_id=3779, title='Insulting Gesture', gold_cost=0, focus_value=3, keywords=[Favor, Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Political Open:</b> A target Stronghold's abilities may not be used. If it is your turn, bow it."
Interference = Strategy(card_id=3785, title='Interference', focus_value=4, traits=[], abilities=[], legality=[TwentyFestivalsEdition, EmperorEdition, CelestialEdition, OnyxEdition, ModernEdition])
"<b>Reaction:</b> After another player's action targets your performing Samurai: Negate his bowing and movement from the action's effects.<br><b>Reaction:</b> After a Fear action targets your performing Samurai: Negate its effects."
Know_No_Fear = Strategy(card_id=4481, title='Know No Fear', gold_cost=0, focus_value=3, keywords=[Courage, BushidoVirtue], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Open:</b> Bow your performing Samurai: Choose a player. He chooses a face-up Personality in one of his provinces. Turn the Personality face-down.'
Know_Their_Minds = Strategy(card_id=4487, title='Know Their Minds', gold_cost=0, focus_value=2, keywords=[DarkVirtue, Insight], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Reaction:</b> After engaging, choose your performing unbowed opposed Personality at the current battlefield: Create two 1F <b>Shadowlands &#149; Undead</b> Followers and attach them to him. Lose 1 Honor.'
Nakanu_Technique = Strategy(card_id=5506, title='Nakanu Technique', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Ninja and target an enemy Personality or Follower: Give it -4F. After this battle ends, if this card is in your discard pile, you may put it into your hand.'
Never_Safe = Strategy(card_id=5535, title='Never Safe', gold_cost=0, focus_value=1, keywords=[Ninja], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Samurai: Attach an attachment in your hand to him, paying all costs but paying 4 less Gold.<br><b>Open:</b> Choose your performing Samurai with an attachment: Straighten his unit.'
On_the_Hunt = Strategy(card_id=5704, title='On the Hunt', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> After a battle's resolution ends, choose one or two performing Personalities at the current battlefield: Straighten their units. They will not bow from the battle's resolution."
Redoubled_Attack = Strategy(card_id=6222, title='Redoubled Attack', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Bow your performing Courtier at any location: The Attacker may target any of his Personalities at the current battlefield and move them home. He loses 1 Honor for each of his Personalities there that this did not move, then dishonors them.'
Scandalous_Rumors = Strategy(card_id=6488, title='Scandalous Rumors', gold_cost=0, focus_value=3, keywords=[Political], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'As a Focus Effect: After this duel ends, give its winner -3F.<br><b>Limited:</b> Target your discarded Personality: Discard a card from one of your provinces and refill it face-up with the Personality.<br><b>Open:</b> Give each of your provinces +2 strength.'
Scavenging_Party = Strategy(card_id=6491, title='Scavenging Party', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'While at this battlefield, Cavalry cards have +1F and Infantry cards have -1F.<br><b>Battle:</b> If there is no Terrain in play at the current battlefield: Put this card into play there.'
Shiotome_Plains = Strategy(card_id=7001, title='Shiotome Plains', gold_cost=0, focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Choose your performing unbowed Ninja Personality and target an enemy card: Bow it. You may discard a card in the current battlefield's province."
Silent_Terror = Strategy(card_id=7261, title='Silent Terror', gold_cost=0, focus_value=1, keywords=[Ninja], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'You have the ability, "<b>Water Battle:</b> If any enemy units are at the current battlefield, choose your performing Water Shugenja: Move him there. You may take an additional Battle action which he must perform."<br><b>Limited:</b> Put this card into play. Discard all your other Kata.'
Skipping_the_Puddle = Strategy(card_id=7285, title='Skipping the Puddle', gold_cost=0, focus_value=3, keywords=[Kata, Water], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Choose your performing unbowed Personality: If he is a Berserker, permanently give him +2F and the ability, "<b>Reaction:</b> After another player\'s action targets this Personality: Delay his destruction from the action\'s effects until before this turn ends." Otherwise, permanently give him <b>Berserker</b>.'
Spirit_of_the_Berserker = Strategy(card_id=7420, title='Spirit of the Berserker', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Choose your performing unbowed Personality: If he is a Duelist, permanently give him the ability, "<b>Iaijutsu Battle:</b> Target an enemy Personality: This Personality duels him. Move the duel\'s loser home." Otherwise, permanently give him <b>Duelist</b>.'
Spirit_of_the_Duelist = Strategy(card_id=7423, title='Spirit of the Duelist', gold_cost=0, focus_value=4, keywords=[Iaijutsu], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Choose your performing unbowed Personality: If he is a Monk, permanently give him the ability, "<b>Battle:</b> Target an enemy Personality without Armor: Bow him." Otherwise, permanently give him <b>Monk</b>.'
Spirit_of_the_Monk = Strategy(card_id=7424, title='Spirit of the Monk', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Choose your performing unbowed Personality: If he is a Paragon, permanently give him the ability, "<b>Battle:</b> Target an enemy Personality with either equal or lower Force, or equal or lower Personal Honor: Bow him." Otherwise, permanently give him <b>Paragon</b>.'
Spirit_of_the_Paragon = Strategy(card_id=7425, title='Spirit of the Paragon', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Choose your performing unbowed Personality: If he is a Scout, permanently give him the ability, "<b>Battle:</b> Bow this Personality unless you have Reconnaissance: Ranged 4 Attack." Otherwise, permanently give him <b>Scout</b>.'
Spirit_of_the_Scout = Strategy(card_id=7426, title='Spirit of the Scout', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Limited:</b> Choose your performing unbowed Personality: If he is a Yojimbo, permanently give him the ability, "<b>Reaction:</b> After another player\'s action targets one of your Personalities at this Personality\'s location: The action targets this Personality instead, if legal." Otherwise, permanently give him <b>Yojimbo</b>.'
Spirit_of_the_Yojimbo = Strategy(card_id=7430, title='Spirit of the Yojimbo', gold_cost=0, focus_value=4, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Battle:</b> Choose your performing unbowed Siege Personality, and target a card with Force lower than or equal to the current battlefield's province's strength in a unit: Bow or straighten the card. Gain 2 Honor."
Strategic_Sacrifice = Strategy(card_id=7524, title='Strategic Sacrifice', gold_cost=0, focus_value=4, keywords=[Siege], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Kensai and target an enemy Personality without Weapons: Reduce his Force to 0. While your Kensai has a Weapon, actions the Personality performs may not target your performer.'
Superior_Reach = Strategy(card_id=7656, title='Superior Reach', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Paragon and target an enemy Personality with equal or lower Personal Honor: Bow him. Gain 2 Honor.'
Surety_of_Purpose = Strategy(card_id=7664, title='Surety of Purpose', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Political Reaction:</b> After the resolution of a battle at a province, if you destroyed any enemy units or a province in that resolution: The battle's loser loses 4 Honor.<br><b>Battle:</b> Choose your performing Magistrate: Straighten him."
Tales_of_Dishonor = Strategy(card_id=7753, title='Tales of Dishonor', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle/Open:</b> Choose your performing unbowed Monk and target a Personality whose Force is different from his own base Force: Bow or straighten him.'
The_Weakness_of_Man = Strategy(card_id=8425, title='The Weakness of Man', gold_cost=0, focus_value=2, keywords=[Kiho], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing Personality: Straighten him.<br><b>Battle/Open:</b> Choose your performing Personality: Negate all current and new Force penalties on him.'
Tireless_Efforts = Strategy(card_id=8496, title='Tireless Efforts', gold_cost=0, focus_value=1, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"As a Focus Effect: Negate any destruction for losing this duel. After this duel ends, its winner's controller gains 2 Honor.<br><b>Reaction:</b> After another player's Iaijutsu action targets your Personality: Negate his destruction from the action's effects."
To_First_Blood = Strategy(card_id=8500, title='To First Blood', gold_cost=0, focus_value=3, keywords=[Iaijutsu], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Commander and target an enemy card with as many or fewer Followers: Bow it. Negate its next straightening <i>(this turn)</i>.'
Unexpected_Support = Strategy(card_id=8977, title='Unexpected Support', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Open:</b> Destroy your performing Ancestor Personality and target a Personality: Bow him. Negate his straightening until your next Events Phase begins.<br><b>Limited:</b> If you control an Ancestor Personality: Gain 2 Honor. Each player who does not control an Ancestor Personality loses 2 Honor.'
Visitation = Strategy(card_id=9172, title='Visitation', gold_cost=0, focus_value=2, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Fire Kiho Battle:</b> Bow your target performing Tattooed Monk to target an enemy Personality with equal or lower Chi. Destroy a card without attachments in his unit. Straighten your Personality if he is Fire and this destroyed an attachment.'
Volcano_Tattoo = Strategy(card_id=9186, title='Volcano Tattoo', gold_cost=0, focus_value=2, keywords=[Fire, Kiho, Tattoo], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> Choose your performing unbowed Spirit and target an enemy Personality: Move him home. This movement will not be negated.'
Wrathful_Ancestor = Strategy(card_id=9390, title='Wrathful Ancestor', gold_cost=0, focus_value=1, keywords=[Fear], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
'<b>Battle:</b> If any enemy units are at the current battlefield, choose your performing Personality in one of your provinces: Bring him into play at the current battlefield, paying all costs but paying 6 less Gold. After the battle ends, if he is in play, discard all his attachments and put him into one of your provinces, face-up, discarding any card there.'
Your_Clan_Needs_You = Strategy(card_id=9687, title='Your Clan Needs You!', gold_cost=0, focus_value=3, traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])