from __future__ import annotations
from .common import Strategy
from l5r_auto.keywords import Courage, Kata, Kharmic, Terrain
from l5r_auto.legality import IvoryEdition, ModernEdition, TwentyFestivalsEdition
'<b>Unstoppable Battle, :g1::</b> Move home a target defending Personality. <i>(Other players cannot Interrupt Unstoppable actions.)</i>'
A_Desperate_Struggle = Strategy(card_id=11978, title='A Desperate Struggle', focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"As a Focus Effect, both the winner and loser of this duel gain 1 Honor.<br><b>Interrupt:</b> If the action is another player's, after it destroys your defending Follower or Personality, give your target Personality +2F and <b>Resilient</b>, and gain 2 Honor. <i>(Once per game per card, a Resilient card does not die in battle resolution.)</i>"
A_Good_Death = Strategy(card_id=11980, title='A Good Death', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Invest :g2:: Draw a card. <i>(Increase the Gold Cost by the Invest cost to get the effect, once.)</i><br><b>Political Open:</b> The abilities on two target Dynasty or Fate cards <i>(in play)</i> cannot be used.'
A_New_Alliance = Strategy(card_id=11985, title='A New Alliance', focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Political Open:</b> Bow your target unbowed Personality and target another player's Personality; Courtiers have +1C during this action. Target and show the top two cards of each Fate deck. The one player whose targeted cards have the highest total Focus Value and Chi, or you if tied, puts his two Fate cards into his hand."
Battle_of_Wits = Strategy(card_id=11987, title='Battle of Wits', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Fortifications at this Province give no bonuses and their abilities may not be used. Defending Personalities have -1F.<br><b>Battle/Engage:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play.'
Besieged_Fortifications = Strategy(card_id=12007, title='Besieged Fortifications', focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Discipline :g2:. <i>(Pay 2 Gold to play, then remove from the game, this Discipline in your discard.)</i><br><b>Absent Interrupt:</b> If the action is from a Strategy, negate any movement from the action's effects."
Brazen_Disregard = Strategy(card_id=12004, title='Brazen Disregard', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Your Followers out of play have <b>Reserve</b>. <i>(You may Equip a Reserve attachment, if it would be opposed, as a Battle action.)</i><br><b>Open:</b> Put this Kata into play. Discard your other Kata in play.'
Bring_them_Forward = Strategy(card_id=11990, title='Bring them Forward', focus_value=2, keywords=[Courage, Kata], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"After you discard this Strategy from a Kharmic action, you may target and discard a Kata.<br><b>Open, [*]:</b> Straighten your target bowed Personality. If his last bowing was from another player's card effect and you paid two Gold for this action, draw a card, and you may target and discard a Kata."
Cautious_Contemplation = Strategy(card_id=12014, title='Cautious Contemplation', focus_value=4, keywords=[Kharmic], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Discipline :g1:<br><b>Interrupt:</b> Negate all Force bonuses and penalties from the action.<br><b>Battle:</b> Give your target Samurai <b>Conqueror</b>. Straighten his unit after this battle resolves. <i>(A Conqueror's unit doesn't bow after battle.)</i>"
Courage_Beyond_Question = Strategy(card_id=12015, title='Courage Beyond Question', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Straighten your target Personality. Dishonor him. Lose 2 Honor. You may take an additional action.'
Dirty_Tricks = Strategy(card_id=12000, title='Dirty Tricks', focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"As a Focus Effect, remove <b>Duelist</b> from the Personality facing yours in this duel.<br><b>Battle:</b> Target your unbowed Personality, and bow him if he's defending. Move home a target enemy Personality with lower Chi. Gain 1 Honor if your Personality is a Duelist."
Drawing_First_Blood = Strategy(card_id=11995, title='Drawing First Blood', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Open, :g2::</b> Target your unbowed Personality and bow him unless he is Dragon Clan or a Magistrate. Look at a number of Fate cards on top of your deck equal to his Chi. Put one in your hand. Put the rest at the bottom of the deck in any order.'
Emerald_Ascension = Strategy(card_id=11981, title='Emerald Ascension', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"You may only play one Escalating Violence per battle.<br><b>Interrupt:</b> If the action is another player's and Battle, after the first time it destroys one of your cards, target an enemy Personality. Your Personalities have +1F/+1C while opposing the target <i>(this turn)</i>."
Escalating_Violence = Strategy(card_id=12017, title='Escalating Violence', focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Discipline :g2: <i>(Pay 2 Gold to play, then remove from the game, this Discipline in your discard.)</i><br><b>Kiho Absent Battle:</b> If he would be opposed, move to the current battlefield your target Monk or Shugenja at home. Straighten him as he moves.'
Honed_to_a_Razors_Edge = Strategy(card_id=12011, title="Honed to a Razor's Edge", focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Unstoppable Battle:</b> Fear 3. <i>(Other players cannot Interrupt Unstoppable actions. Bow a target enemy Follower or Personality without Followers with 3 or lower Force.)</i>'
In_Defense = Strategy(card_id=12006, title='In Defense', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Open:</b> Until he leaves play, give your target Human Shugenja the ability, "<b>Home Battle:</b> Straighten one of this Shugenja\'s Spells. You may use its abilities again this turn. If you are a Phoenix Clan player, you may take an additional action."'
Jade_Ascension = Strategy(card_id=11983, title='Jade Ascension', focus_value=3, keywords=[Courage], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'After you discard this Strategy from a Courage action, gain 1 Honor.<br><b>Favor Political Open:</b> If this Strategy is in your discard pile, discard the Imperial Favor and remove this Strategy from the game to draw a card.'
New_Factors = Strategy(card_id=11998, title='New Factors', focus_value=2, keywords=[Courage], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<i>(<b>Repeatable Interrupt:</b> Discard a Courage card to give a Fear effect +2 or -2 strength.)</i><br><b>Battle:</b> Give your target Personality <b>Conqueror</b>. If you control a Courtier or Shugenja, you may target and give your Yojimbo Personality <b>Conqueror</b>.'
No_One_of_Consequence = Strategy(card_id=11999, title='No One of Consequence', focus_value=1, keywords=[Courage], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'All players have, "<b>Open:</b> Bow your target unbowed Personalities and Followers with 5 or more total Force to discard an Obsidian Ascension, putting any cards under it into their owner\'s hand."<br><b>Open:</b> Put this Strategy into play and put a target Weapon <i>(in play)</i> under it. Gain 1 Honor if you are Lion Clan.'
Obsidian_Ascension = Strategy(card_id=11982, title='Obsidian Ascension', focus_value=4, keywords=[Courage, Kharmic], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'After you discard <i>(not focus)</i> this Strategy during a battle, draw a card.'
Ongoing_Division = Strategy(card_id=12010, title='Ongoing Division', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Before this battle resolves, you may target a Personality <i>(at any location)</i> who assigned to this battlefield, and move him here.<br><b>Battle:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play.'
Open_Ground = Strategy(card_id=12002, title='Open Ground', focus_value=2, keywords=[Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Destroy a target Fortification at this battlefield.<br><b>Battle:</b> Give a target Follower or Personality -5F. Lose Honor equal to half your starting Honor, rounded down.'
Overwhelming_Offense = Strategy(card_id=12009, title='Overwhelming Offense', focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Open:</b> If you control one or no Rings, your target unbowed Personality challenges another player's target Personality. Spells and Kihos have +1FV during the duel. The loser must declare an attack this turn <i>(if legal)</i> and must assign his Personality from the duel, opposing an army if possible."
Priestly_Feud = Strategy(card_id=11996, title='Priestly Feud', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Courtesy: This Strategy's ability is a <b>Battle/Open</b>. <i>(Courtesy traits do not take effect if you went first.)</i><br><b>Battle:</b> Straighten your target Personality, and straighten his Weapons if he is a Kensai."
Return_to_Your_Feet = Strategy(card_id=12003, title='Return to Your Feet', focus_value=1, keywords=[Courage], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"This Strategy's ability is <b>Battle/Engage</b> if you control a Scout at this battlefield.<br><b>Battle:</b> Search your Fate deck for a Terrain, show it, and put it in your hand."
Scouting_Amid_the_Snow = Strategy(card_id=11988, title='Scouting Amid the Snow', focus_value=3, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'After you discard this card from a Kharmic action, you may straighten or bow a Ring or Void card.<br><b>Kiho Void Open:</b> Bow your target unbowed Monk or Shugenja. Look at the top three cards of your Fate deck. Put one of them into your hand. Put this Strategy into your deck where that card was.'
Self_and_No_Self = Strategy(card_id=12005, title='Self and No Self', focus_value=4, keywords=[Kharmic], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Courtesy: This Strategy's Ranged Attack has +1 strength. <i>(Courtesy traits do not take effect if you went first.)</i><br><b>Unstoppable Battle, :g1::</b> Target your unbowed Samurai. Ranged Attack equal to his Personal Honor."
Serenity = Strategy(card_id=11979, title='Serenity', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Unstoppable Battle:</b> Give a target attacking Personality -4F. <i>(Other players cannot Interrupt Unstoppable actions.)</i>'
Sinister_Deception = Strategy(card_id=12018, title='Sinister Deception', focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Unstoppable Battle:</b> Give a target enemy Follower or Personality -2F. You may target your Scout to take an additional action. <i>(Other players cannot Interrupt Unstoppable actions.)</i>'
Springing_the_Ambush = Strategy(card_id=11993, title='Springing the Ambush', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Battle:</b> Target your unbowed Personality. Bow him or, if he is a Yojimbo, your unbowed Courtier or Shugenja at any location, to make a Melee Attack equal to your targeted Personality's Chi."
Stay_Behind_Me = Strategy(card_id=11994, title='Stay Behind Me', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Discipline :g2:.<br>Players discard a card after each time one of their own actions moves a Personality home. After a player's action destroys this Terrain, he discards a card.<br><b>Battle/Engage:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play."
Sulphurous_Swamps = Strategy(card_id=11989, title='Sulphurous Swamps', focus_value=1, keywords=[Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Kolat Open:</b> Permanently set your target Human Personality\'s Personal Honor to 0, give him <b><b>Courtier &#149; Kolat</b>, </b>and give him the ability "<b>Kolat Political Open, :bow::</b> Target a Personality controlled by the active player. His controller may pay 4 Gold. If he does not, bow the target." Lose 1 Honor unless you are Dragon Clan.'
The_Soul_of_Man = Strategy(card_id=11984, title='The Soul of Man', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Courtesy: Discipline :g1:. <i>(Courtesy traits do not take effect if you went first. Pay 1 Gold to play, then remove from the game, this Discipline in your discard.)</i><br><b>Absent Battle:</b> Target your Personality at home who assigned to the current battlefield <i>(this turn)</i>. Move him there.'
The_Thrill_of_Daring = Strategy(card_id=11986, title='The Thrill of Daring', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"<b>Battle:</b> Bow your target unbowed Weapon to reduce a target enemy Follower's or Personality's Force by the Weapon's positive Force Modifier. You may remove one of the enemy card's abilities <i>(this turn)</i> if your Weapon is attached to a Kensai."
Two_Swords_One_Cut = Strategy(card_id=12012, title='Two Swords, One Cut', focus_value=2, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'After you discard this Strategy for a Kharmic action, you may take the Imperial Favor if you have higher Family Honor than any other player.<br><b>Political Open:</b> Even if this Strategy is in your discard pile, put your target discarded <i>(not dead)</i> Personality into one of your Provinces, discarding any card there. Remove this Strategy from the game.'
Undermining_the_Otomo = Strategy(card_id=12016, title='Undermining the Otomo', focus_value=3, keywords=[Kharmic], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Put your target Ring into your hand. Destroy a target enemy card without attachments.'
Undone_by_the_Enlightened = Strategy(card_id=11991, title='Undone by the Enlightened', focus_value=4, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Battle:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play. If this destroyed a Terrain, draw a card.'
Unexpected_Attack = Strategy(card_id=12013, title='Unexpected Attack', focus_value=3, keywords=[Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'<b>Open:</b> Choose another player. Before each Honor gain or loss from his cards in play, he may bow one of his unbowed Holdings; if he does not bow a Holding, negate the gain or loss. These effects will not be prevented.'
Unforeseen_Cost = Strategy(card_id=12001, title='Unforeseen Cost', focus_value=2, keywords=[Courage, Kharmic], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"Courtesy: You may take an additional action after resolving this Strategy's action. <i>(Courtesy traits do not take effect if you went first.)</i><br>Your Personalities have <b>Resilient</b>.<br><b>Battle:</b> Destroy a Terrain <i>(if able)</i>. Put this Terrain into play."
Valiant_Defense = Strategy(card_id=12008, title='Valiant Defense', focus_value=4, keywords=[Terrain], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
"As a Focus Effect, exchange the Focus Values of this Strategy and one of the other player's focused cards.<br><b>Interrupt:</b> Give a Melee or Ranged Attack -2 strength."
We_Are_Not_Yet_Beaten = Strategy(card_id=11992, title='We Are Not Yet Beaten', focus_value=3, keywords=[Kharmic], traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])
'Invest :g1:: Draw a card. <i>(Increase the Gold Cost by the Invest cost to get the effect, once.)</i><br><b>Battle/Open:</b> Give your target Personality +1F/+2C.'
Zazen_Meditation = Strategy(card_id=11997, title='Zazen Meditation', focus_value=1, traits=[], abilities=[], legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition])