from __future__ import annotations

from l5r_auto.clans import NinjaFaction, ScorpionClan
from l5r_auto.keywords import (
    ClanChampion,
    Courtier,
    Destined,
    Experienced,
    Loyal,
    Magistrate,
    Ninja,
    Samurai,
    ShojusSoul,
    Sociopath,
    SoulOf,
    Spy,
    ThePoisonMask,
    Unique,
    Yojimbo,
)
from l5r_auto.legality import IvoryEdition, ModernEdition, TwentyFestivalsEdition

from ..common import Personality

Bayushi_Akane = Personality(
    id=11210,
    title="Bayushi Akane",
    force=0,
    chi=3,
    personal_honor=2,
    gold_cost=2,
    honor_requirement=0,
    clan=[ScorpionClan],
    keywords=[Courtier, SoulOf("Bayushi Kurumi")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Bayushi_Dakatsu = Personality(
    id=11211,
    title="Bayushi Dakatsu",
    force=3,
    chi=3,
    personal_honor=2,
    gold_cost=5,
    honor_requirement=1,
    clan=[ScorpionClan],
    keywords=[Magistrate, Samurai, SoulOf("Shosuro Takagi"), Yojimbo],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Bayushi_Masashi = Personality(
    id=11212,
    title="Bayushi Masashi",
    force=3,
    chi=2,
    personal_honor=1,
    gold_cost=5,
    honor_requirement=None,
    clan=[ScorpionClan],
    keywords=[Samurai, Yojimbo],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Bayushi_Meiko = Personality(
    id=11213,
    title="Bayushi Meiko",
    force=4,
    chi=3,
    personal_honor=1,
    gold_cost=8,
    honor_requirement=None,
    clan=[ScorpionClan],
    keywords=[Courtier, Samurai, SoulOf("Bayushi Maemi")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Bayushi_Nitoshi_the_Poison_Mask_Experienced_2 = Personality(
    id=11214,
    title="Bayushi Nitoshi, the Poison Mask",
    force=5,
    chi=5,
    personal_honor=1,
    gold_cost=12,
    honor_requirement=None,
    clan=[ScorpionClan, NinjaFaction],
    keywords=[
        Experienced("2"),
        Loyal,
        Unique,
        ClanChampion,
        Courtier,
        Ninja,
        Samurai,
        ShojusSoul,
        Sociopath,
        ThePoisonMask,
    ],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Bayushi_Shizuka = Personality(
    id=11215,
    title="Bayushi Shizuka",
    force=2,
    chi=3,
    personal_honor=1,
    gold_cost=5,
    honor_requirement=None,
    clan=[ScorpionClan],
    keywords=[Courtier, Samurai, SoulOf("Bayushi Saya")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Shosuro_Hotaka = Personality(
    id=11216,
    title="Shosuro Hotaka",
    force=0,
    chi=3,
    personal_honor=1,
    gold_cost=4,
    honor_requirement=None,
    clan=[ScorpionClan],
    keywords=[Destined, Courtier],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Shosuro_Keiichi = Personality(
    id=11217,
    title="Shosuro Keiichi",
    force=3,
    chi=4,
    personal_honor=1,
    gold_cost=7,
    honor_requirement=None,
    clan=[ScorpionClan, NinjaFaction],
    keywords=[Ninja, Samurai, SoulOf("Shosuro Osamito")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Shosuro_Tagiso = Personality(
    id=11218,
    title="Shosuro Tagiso",
    force=3,
    chi=4,
    personal_honor=1,
    gold_cost=6,
    honor_requirement=None,
    clan=[ScorpionClan, NinjaFaction],
    keywords=[Ninja, Samurai, SoulOf("Shosuro Hihiko")],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
Shosuro_Tosaku = Personality(
    id=11219,
    title="Shosuro Tosaku",
    force=3,
    chi=4,
    personal_honor=1,
    gold_cost=6,
    honor_requirement=None,
    clan=[ScorpionClan],
    keywords=[Samurai, SoulOf("Bayushi Tai"), Spy],
    traits=[],
    abilities=[],
    legality=[IvoryEdition, TwentyFestivalsEdition, ModernEdition, ModernEdition],
)
