from __future__ import annotations
from ..common import Personality
from l5r_auto.clans import BrotherhoodOfShinsei, PhoenixClan
from l5r_auto.keywords import Acolyte, Air, Alchemist, BlindPhoenix, Cavalry, ClanChampion, Daimyo, Duelist, Earth, ElementalMaster, Enlightened, Experienced, Fire, Henshin, Inquisitor, Ishiken, Loyal, Magistrate, Monk, Samurai, ShibasSoul, Shugenja, SoulOf, Unique, Void, Water, Yojimbo
from l5r_auto.legality import CelestialEdition, EmperorEdition, ModernEdition
'<b>Void Reaction:</b> After Ryo enters play from a Province, refill it face-up.'
Agasha_Ryo = Personality(card_id=153, title='Agasha Ryo', force=2, chi=2, personal_honor=2, gold_cost=5, honor_requirement=5, clan=[PhoenixClan], keywords=[Acolyte, Shugenja, SoulOf('Agasha Seruma'), Void], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
Asako_Niou = Personality(card_id=571, title='Asako Niou', force=2, chi=2, personal_honor=2, gold_cost=4, honor_requirement=4, clan=[PhoenixClan, BrotherhoodOfShinsei], keywords=[Henshin, Monk, Void], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> Melee 4 Attack that you may compare against base Force if the target has no attachments.'
Asako_Nobunori = Personality(card_id=572, title='Asako Nobunori', force=5, chi=2, personal_honor=1, gold_cost=8, honor_requirement=0, clan=[PhoenixClan, BrotherhoodOfShinsei], keywords=[Fire, Henshin, Monk], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
Asako_Rinshi = Personality(card_id=577, title='Asako Rinshi', force=3, chi=4, personal_honor=4, gold_cost=7, honor_requirement=6, clan=[PhoenixClan], keywords=[Air, Inquisitor, Magistrate, Shugenja], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Open:</b> Target another player's Personality: Give him <b>Kolat, Ninja, </b>or<b> Shadowlands</b>.<br><b>Battle:</b> Target an enemy Personality: Bow him. If he is Kolat, Ninja, or Shadowlands, choose a player, who gains or loses 2 Honor."
Asako_Tsunefusa = Personality(card_id=590, title='Asako Tsunefusa', force=2, chi=4, personal_honor=3, gold_cost=7, honor_requirement=8, clan=[PhoenixClan], keywords=[Earth, Inquisitor, Magistrate, Shugenja], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'Ume has +1F while she has a Spell.<br><b>Battle:</b> Ranged 4 Attack.'
Asako_Ume = Personality(card_id=592, title='Asako Ume', force=3, chi=3, personal_honor=2, gold_cost=7, honor_requirement=4, clan=[PhoenixClan], keywords=[Fire, Shugenja, SoulOf('Isawa Furiko')], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Battle:</b> Target a Personality whose Force is different from his base Force: Bow or straighten him.'
Asako_Yorisada = Personality(card_id=595, title='Asako Yorisada', force=4, chi=2, personal_honor=3, gold_cost=7, honor_requirement=6, clan=[PhoenixClan, BrotherhoodOfShinsei], keywords=[Earth, Henshin, Monk], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"Your other Personalities at Kimi's location that share any element keywords with her or with any of her Spells have +1F.<br><b>Reaction:</b> Even if Kimi is bowed, after the resolution of an action that put any cards into another player's hand: That player chooses and discards a card from his hand."
Isawa_Kimi_Experienced_2 = Personality(card_id=3847, title='Isawa Kimi', force=4, chi=5, personal_honor=3, gold_cost=10, honor_requirement=6, clan=[PhoenixClan], keywords=[Enlightened, Experienced('2'), Loyal, Unique, ElementalMaster, Shugenja, Void], traits=[], abilities=[], legality=[EmperorEdition, CelestialEdition, ModernEdition])
"<b>Reaction:</b> After another player's action targets your Earth Shugenja at Norimichi's location: Negate the Shugenja's destruction from the action's effects.<br><b>Battle:</b> Until this battle ends, while there are any units in your army, your army has +5 total Force."
Isawa_Norimichi = Personality(card_id=3881, title='Isawa Norimichi', force=4, chi=5, personal_honor=3, gold_cost=9, honor_requirement=6, clan=[PhoenixClan], keywords=[Loyal, Unique, Earth, ElementalMaster, Shugenja], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
Isawa_Shunsuko = Personality(card_id=3904, title='Isawa Shunsuko', force=3, chi=2, personal_honor=2, gold_cost=6, honor_requirement=4, clan=[PhoenixClan], keywords=[Cavalry, Shugenja, SoulOf('Isawa Yutako'), Water], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Void Limited:</b> Look at the top card of your Fate deck. You may put it at the bottom of the deck.'
Isawa_Tamaki = Personality(card_id=3918, title='Isawa Tamaki', force=4, chi=3, personal_honor=2, gold_cost=7, honor_requirement=5, clan=[PhoenixClan], keywords=[Ishiken, Shugenja, SoulOf('Isawa Hachiko'), Void], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
Isawa_Tomohiro = Personality(card_id=3930, title='Isawa Tomohiro', force=2, chi=4, personal_honor=4, gold_cost=6, honor_requirement=6, clan=[PhoenixClan], keywords=[Air, Alchemist, Ishiken, Shugenja, SoulOf('Isawa Kumai'), Void], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
'<b>Iaijutsu Battle:</b> Target an enemy card without attachments: Bow it.'
Shiba_Kataken = Personality(card_id=6768, title='Shiba Kataken', force=5, chi=4, personal_honor=3, gold_cost=9, honor_requirement=5, clan=[PhoenixClan], keywords=[Duelist, Samurai, SoulOf('Shiba Goto'), Yojimbo], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Reaction:</b> When an action would target your Shugenja at Sansesuke's location, bow Sansesuke: The action targets him instead, if legal."
Shiba_Sansesuke = Personality(card_id=6803, title='Shiba Sansesuke', force=2, chi=3, personal_honor=1, gold_cost=4, honor_requirement=2, clan=[PhoenixClan], keywords=[Samurai, SoulOf('Shiba Danjuro'), Yojimbo], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])
"<b>Reaction:</b> Twice per battle, after the resolution of another player's Battle action: Tsukimi displays incredible reflexes. Move her home or to the current battlefield.<br><b>Battle:</b> Melee 6 Attack, with +2 strength if you control a Shugenja."
Shiba_Tsukimi_Experienced_4 = Personality(card_id=6818, title='Shiba Tsukimi', force=8, chi=6, personal_honor=5, gold_cost=12, honor_requirement=20, clan=[PhoenixClan], keywords=[Duelist, Experienced('4'), Loyal, Unique, BlindPhoenix, ClanChampion, Daimyo, Samurai, ShibasSoul], traits=[], abilities=[], legality=[EmperorEdition, ModernEdition])