from __future__ import annotations

from l5r_auto.clans import PhoenixClan
from l5r_auto.keywords import (
    Air,
    Alchemist,
    Artisan,
    Cavalry,
    Commander,
    Daimyo,
    Duelist,
    Earth,
    Experienced,
    Fire,
    Inquisitor,
    Loyal,
    Magistrate,
    Naval,
    Samurai,
    Shugenja,
    SoulOf,
    Unique,
    Water,
    Yojimbo,
)
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition

from ..common import Personality

Agasha_Shikeno = Personality(
    card_id=12140,
    title="Agasha Shikeno",
    force=3,
    chi=4,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=4,
    clan=[PhoenixClan],
    keywords=[Air, Alchemist, Fire, Shugenja, SoulOf("Asako Hoshimi")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Agasha_Tameko = Personality(
    card_id=12141,
    title="Agasha Tameko",
    force=3,
    chi=4,
    personal_honor=2,
    gold_cost=8,
    honor_requirement=4,
    clan=[PhoenixClan],
    keywords=[Commander, Shugenja, SoulOf("Agasha Tomioko"), Water],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Asako_Hiribe = Personality(
    card_id=12142,
    title="Asako Hiribe",
    force=2,
    chi=4,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=6,
    clan=[PhoenixClan],
    keywords=[Earth, Inquisitor, Magistrate, Shugenja],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Asako_Tsunefusa_Experienced = Personality(
    card_id=12143,
    title="Asako Tsunefusa",
    force=3,
    chi=4,
    personal_honor=3,
    gold_cost=9,
    honor_requirement=8,
    clan=[PhoenixClan],
    keywords=[
        Loyal,
        Unique,
        Daimyo,
        Earth,
        Experienced("1"),
        Inquisitor,
        Magistrate,
        Shugenja,
    ],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Isawa_Akime = Personality(
    card_id=12144,
    title="Isawa Akime",
    force=1,
    chi=3,
    personal_honor=3,
    gold_cost=4,
    honor_requirement=8,
    clan=[PhoenixClan],
    keywords=[Air, Artisan, Shugenja],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Isawa_Haruge = Personality(
    card_id=12145,
    title="Isawa Haruge",
    force=3,
    chi=3,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=2,
    clan=[PhoenixClan],
    keywords=[Earth, Shugenja, SoulOf("Isawa Itsuoko")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Isawa_Kageharu = Personality(
    card_id=12146,
    title="Isawa Kageharu",
    force=1,
    chi=2,
    personal_honor=2,
    gold_cost=3,
    honor_requirement=6,
    clan=[PhoenixClan],
    keywords=[Loyal, Naval, Shugenja, SoulOf("Isawa Mizuhiko"), Water],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Isawa_Mochiko = Personality(
    card_id=12147,
    title="Isawa Mochiko",
    force=3,
    chi=3,
    personal_honor=3,
    gold_cost=7,
    honor_requirement=2,
    clan=[PhoenixClan],
    keywords=[Cavalry, Shugenja, SoulOf("Isawa Tanaka"), Water],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Isawa_Uzuyumi_Experienced = Personality(
    card_id=12148,
    title="Isawa Uzuyumi",
    force=3,
    chi=4,
    personal_honor=3,
    gold_cost=8,
    honor_requirement=6,
    clan=[PhoenixClan],
    keywords=[Naval, Unique, Commander, Experienced("1"), Shugenja, Water],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Shiba_Danjiro = Personality(
    card_id=12149,
    title="Shiba Danjiro",
    force=2,
    chi=2,
    personal_honor=2,
    gold_cost=5,
    honor_requirement=0,
    clan=[PhoenixClan],
    keywords=[Samurai, SoulOf("Shiba Morihiko"), Yojimbo],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Shiba_Kiyomichi = Personality(
    card_id=12150,
    title="Shiba Kiyomichi",
    force=2,
    chi=3,
    personal_honor=3,
    gold_cost=6,
    honor_requirement=12,
    clan=[PhoenixClan],
    keywords=[Duelist, Samurai, SoulOf("Shiba Sakishi"), Yojimbo],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
