from __future__ import annotations
from dataclasses import dataclass
from l5r_auto.card import Ability, Trait
from l5r_auto.cards.personalities.common import Personality
from l5r_auto.clans import PhoenixClan
from l5r_auto.keywords import Air, Alchemist, Artisan, Cavalry, Commander, Daimyo, Duelist, Earth, Experienced, Fire, Inquisitor, Loyal, Magistrate, Naval, Samurai, Shugenja, SoulOf, Unique, Water, Yojimbo
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition
Agasha_Shikeno = Personality(id=12140, title='Agasha Shikeno', force=3, chi=4, honor_requirement=4, personal_honor=3, gold_cost=6, clan=[PhoenixClan], keywords=[Air, Alchemist, Fire, Shugenja, SoulOf('Asako Hoshimi')], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Agasha_Tameko = Personality(id=12141, title='Agasha Tameko', force=3, chi=4, honor_requirement=4, personal_honor=2, gold_cost=8, clan=[PhoenixClan], keywords=[Commander, Shugenja, SoulOf('Agasha Tomioko'), Water], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Asako_Hiribe = Personality(id=12142, title='Asako Hiribe', force=2, chi=4, honor_requirement=6, personal_honor=3, gold_cost=6, clan=[PhoenixClan], keywords=[Earth, Inquisitor, Magistrate, Shugenja], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Asako_Tsunefusa_Experienced = Personality(id=12143, title='Asako Tsunefusa', force=3, chi=4, honor_requirement=8, personal_honor=3, gold_cost=9, clan=[PhoenixClan], keywords=[Loyal, Unique, Daimyo, Earth, Experienced('1'), Inquisitor, Magistrate, Shugenja], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Isawa_Akime = Personality(id=12144, title='Isawa Akime', force=1, chi=3, honor_requirement=8, personal_honor=3, gold_cost=4, clan=[PhoenixClan], keywords=[Air, Artisan, Shugenja], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Isawa_Haruge = Personality(id=12145, title='Isawa Haruge', force=3, chi=3, honor_requirement=2, personal_honor=3, gold_cost=7, clan=[PhoenixClan], keywords=[Earth, Shugenja, SoulOf('Isawa Itsuoko')], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Isawa_Kageharu = Personality(id=12146, title='Isawa Kageharu', force=1, chi=2, honor_requirement=6, personal_honor=2, gold_cost=3, clan=[PhoenixClan], keywords=[Loyal, Naval, Shugenja, SoulOf('Isawa Mizuhiko'), Water], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Isawa_Mochiko = Personality(id=12147, title='Isawa Mochiko', force=3, chi=3, honor_requirement=2, personal_honor=3, gold_cost=7, clan=[PhoenixClan], keywords=[Cavalry, Shugenja, SoulOf('Isawa Tanaka'), Water], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Isawa_Uzuyumi_Experienced = Personality(id=12148, title='Isawa Uzuyumi', force=3, chi=4, honor_requirement=6, personal_honor=3, gold_cost=8, clan=[PhoenixClan], keywords=[Naval, Unique, Commander, Experienced('1'), Shugenja, Water], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Shiba_Danjiro = Personality(id=12149, title='Shiba Danjiro', force=2, chi=2, honor_requirement=0, personal_honor=2, gold_cost=5, clan=[PhoenixClan], keywords=[Samurai, SoulOf('Shiba Morihiko'), Yojimbo], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])
Shiba_Kiyomichi = Personality(id=12150, title='Shiba Kiyomichi', force=2, chi=3, honor_requirement=12, personal_honor=3, gold_cost=6, clan=[PhoenixClan], keywords=[Duelist, Samurai, SoulOf('Shiba Sakishi'), Yojimbo], traits=[], abilities=[], legality=[ModernEdition, OnyxEdition, TwentyFestivalsEdition])