from __future__ import annotations
from ..common import Personality
from l5r_auto.clans import BrotherhoodOfShinsei, NagaFaction, ShadowlandsFaction, Unaligned
from l5r_auto.keywords import Artisan, BadgerClan, Cavalry, Champion, Commander, Conqueror, Courtier, DiscipleOfPanKu, Dragon, Duelist, Emperor, Expendable, Experienced, Fallen, Fire, Fudo, Imperial, Inexperienced, MadDragon, Monk, Naga, Nonhuman, OrioleClan, Pearl, QueenOfFools, Samurai, Scout, SecondCityGovernor, Shadowlands, Shugenja, Tattooed, TheHandOfSteel, TheStoneBreaker, TheUnbreakable, Unique
from l5r_auto.legality import EmperorEdition, IvoryEdition, ModernEdition
"After Akumasa enters play, lose 2 Honor.<br><b>Open:</b> Target another player's Personality who has a Madness token. After the target attacks this turn, draw a card."
Akumasa = Personality(card_id=10495, title='Akumasa', force=0, chi=3, personal_honor=0, gold_cost=5, honor_requirement=None, clan=[Unaligned], keywords=[DiscipleOfPanKu, Fallen, Shugenja], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
"Usohara's abilities will not be copied.<br><b>Limited, :bow::</b> Search your Dynasty discard pile, then deck, for a Fudo Celestial. Put it into play.<br><b>Limited:</b> Put a Fudo Ring from your hand into play. This counts as playing it by its own text. Remove Usohara from the game."
Asako_Usohara = Personality(card_id=10493, title='Asako Usohara', force=1, chi=5, personal_honor=1, gold_cost=8, honor_requirement=None, clan=[Unaligned, BrotherhoodOfShinsei], keywords=[Unique, Fudo, Monk, Shugenja], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
'<i>(Draw a card after your Expendable card is destroyed.)</i><br>Asp Skirmisher will not join a player who controls a Human Personality.'
Asp_Skirmisher = Personality(card_id=10504, title='Asp Skirmisher', force=2, chi=2, personal_honor=0, gold_cost=2, honor_requirement=None, clan=[Unaligned, NagaFaction], keywords=[Expendable, Naga, Nonhuman, Scout], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
"You ignore Hantei XVI's Honor Requirement if you control the Imperial Favor.<br>After Hantei XVI enters play, search your discard pile or Fate deck for a non-Unique Political Strategy. Show it. Put it in your hand."
Hantei_XVI_Inexperienced = Personality(card_id=10500, title='Hantei XVI', force=2, chi=4, personal_honor=1, gold_cost=7, honor_requirement=10, clan=[Unaligned], keywords=[Unique, Emperor, Imperial, Inexperienced, Samurai], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
"Otani will not enter play if your Family Honor is 0 or above.<br><b>Battle:</b> Otani challenges a target enemy Personality to a duel of Force. Items do not give bonuses or positive Modifiers to Force during the duel. Bow the duel's loser."
Ichiro_Otani_the_Stone_Breaker = Personality(card_id=10494, title='Ichiro Otani, the Stone Breaker', force=6, chi=3, personal_honor=0, gold_cost=6, honor_requirement=None, clan=[Unaligned, ShadowlandsFaction], keywords=[Unique, BadgerClan, Samurai, Shadowlands, TheStoneBreaker], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
'<i>(Draw a card after your Expendable card is destroyed.)</i><br>After Takaki enters play, lose 1 Honor.<br><b>Engage:</b> Give a target card a <b>Madness </b>token.'
Iuchi_Takaki = Personality(card_id=10498, title='Iuchi Takaki', force=0, chi=1, personal_honor=0, gold_cost=4, honor_requirement=None, clan=[Unaligned], keywords=[Cavalry, Expendable, DiscipleOfPanKu, Fallen, Shugenja], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
"After Kokujin enters play, lose 6 Honor unless you are a Spider Clan player.<br><b>Battle:</b> Kokujin challenges a target enemy Personality. Destroy the duel's loser or, if Kokujin wins, you may destroy one of your Personalities <i>(at any location)</i> to take control of the loser <i>(he joins Kokujin's army)</i>."
Kokujin_Inexperienced = Personality(card_id=10486, title='Kokujin', force=4, chi=4, personal_honor=0, gold_cost=11, honor_requirement=None, clan=[Unaligned, BrotherhoodOfShinsei, ShadowlandsFaction], keywords=[Duelist, Unique, Inexperienced, Monk, Shadowlands, Tattooed], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
"After Suikihime enters play, lose 3 Honor.<br>Other players' Political actions may not target Suikihime. Suikihime may not attack.<br><b>Limited, :bow::</b> Search your Dynasty deck for a Fallen Personality. Put him into one of your Provinces face-up, discarding any card currently there."
Otomo_Suikihime_Queen_of_Fools_Experienced = Personality(card_id=10496, title='Otomo Suikihime, Queen of Fools', force=0, chi=3, personal_honor=0, gold_cost=9, honor_requirement=None, clan=[Unaligned], keywords=[Unique, Courtier, Experienced('1'), Fallen, Imperial, QueenOfFools, SecondCityGovernor], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
"<b>Open, :bow::</b> Give a target card a <b>Madness </b>token.<br><b>Limited, :bow::</b> P'an Ku may remain bowed. Take control of a target Personality with more Madness tokens than printed Personal Honor and remove those tokens. The target will not commit seppuku until P'an Ku straightens or leaves play. After P'an Ku does, give control of the target to his owner."
Pan_Ku_Experienced = Personality(card_id=10497, title="P'an Ku", force=0, chi=1, personal_honor=0, gold_cost=10, honor_requirement=None, clan=[Unaligned], keywords=[Cavalry, Unique, Dragon, Experienced('1'), Fallen, MadDragon, Nonhuman], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
'Sengmai enters play ignoring Gold Cost if you control the Ring of Fire.<br>Sengmai will not enter play if your Family Honor is 0 or above.<br>After Sengmai enters play, put a Kiho in your discard pile into your hand.'
Sengmai_the_Unbreakable = Personality(card_id=10499, title='Sengmai, the Unbreakable', force=4, chi=3, personal_honor=0, gold_cost=4, honor_requirement=None, clan=[Unaligned, BrotherhoodOfShinsei, ShadowlandsFaction], keywords=[Unique, Fire, Monk, Shadowlands, TheUnbreakable], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
'<i><i><i><i>(Draw a card after your Expendable card is destroyed.)</i></i></i></i> <br>You have +1 maximum hand size.'
Takujin = Personality(card_id=10492, title='Takujin', force=0, chi=3, personal_honor=0, gold_cost=4, honor_requirement=None, clan=[Unaligned, BrotherhoodOfShinsei], keywords=[Expendable, Fudo, Monk, Shugenja], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
'After The Dark Naga enters play, lose 3 Honor.<br><b>Open, :gstar::</b> Equip a Nonhuman Follower in your hand or discard pile to The Dark Naga, paying 4 less Gold.<br><b>Pearl Battle, :bow::</b> Ranged 9 Attack.'
The_Dark_Naga_Experienced = Personality(card_id=10501, title='The Dark Naga', force=9, chi=6, personal_honor=0, gold_cost=14, honor_requirement=None, clan=[Unaligned, NagaFaction], keywords=[Unique, Champion, Experienced('1'), Naga, Nonhuman, Pearl, Shugenja], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
"While you control three or fewer Personalities, your other Nonhuman Personalities and Followers enter play for 1 less Gold.<br><b>Home Battle:</b> Move your target Personality at any location to The Shakash's location. <i>(Home actions may be used from home.)</i>"
The_Shakash_Experienced = Personality(card_id=10502, title='The Shakash', force=6, chi=2, personal_honor=0, gold_cost=9, honor_requirement=None, clan=[Unaligned, NagaFaction], keywords=[Conqueror, Unique, Commander, Experienced('1'), Naga, Nonhuman], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
'Hayamizu will not join a Scorpion Clan player.<br>Hayamizu has +1F for each Mine you control.'
Tsi_Hayamizu_the_Hand_of_Steel = Personality(card_id=10503, title='Tsi Hayamizu, the Hand of Steel', force=2, chi=3, personal_honor=1, gold_cost=4, honor_requirement=None, clan=[Unaligned], keywords=[Unique, Artisan, OrioleClan, Samurai, TheHandOfSteel], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])
"Zansho will not join a Spider Clan player.<br><b>Battle:</b> Bow Zansho's target unbowed Follower. Ranged Attack with strength equal to its Force, plus 2 if the Ranged Attack targets Daigotsu Arakan."
Zansho_Experienced = Personality(card_id=10505, title='Zansho', force=3, chi=3, personal_honor=3, gold_cost=5, honor_requirement=None, clan=[Unaligned], keywords=[Conqueror, Unique, Commander, Experienced('1'), Samurai], traits=[], abilities=[], legality=[IvoryEdition, EmperorEdition, ModernEdition])