from __future__ import annotations

from l5r_auto.clans import ShadowlandsFaction, Unaligned
from l5r_auto.keywords import (
    Air,
    Cavalry,
    Courtier,
    Dragon,
    DragonflyClan,
    Earth,
    Experienced,
    Fire,
    Magistrate,
    Naval,
    Nonhuman,
    Samurai,
    Shadowlands,
    Shugenja,
    SoulOf,
    Undead,
    Unique,
    Void,
    Water,
)
from l5r_auto.legality import ModernEdition, OnyxEdition, TwentyFestivalsEdition

from ..common import Personality

Air_Dragon_Experienced_3 = Personality(
    id=12171,
    title="Air Dragon",
    force=7,
    chi=5,
    personal_honor=4,
    gold_cost=15,
    honor_requirement=15,
    clan=[Unaligned],
    keywords=[Cavalry, Experienced("3"), Unique, Air, Dragon, Nonhuman, Shugenja],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Earth_Dragon_Experienced_2 = Personality(
    id=12172,
    title="Earth Dragon",
    force=7,
    chi=5,
    personal_honor=4,
    gold_cost=15,
    honor_requirement=15,
    clan=[Unaligned],
    keywords=[Cavalry, Experienced("2"), Unique, Dragon, Earth, Nonhuman, Shugenja],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Fire_Dragon_Experienced_3 = Personality(
    id=12173,
    title="Fire Dragon",
    force=7,
    chi=5,
    personal_honor=4,
    gold_cost=15,
    honor_requirement=15,
    clan=[Unaligned],
    keywords=[Cavalry, Experienced("3"), Unique, Dragon, Fire, Nonhuman, Shugenja],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Haikitsu = Personality(
    id=12174,
    title="Haikitsu",
    force=3,
    chi=3,
    personal_honor=2,
    gold_cost=5,
    honor_requirement=4,
    clan=[Unaligned],
    keywords=[Magistrate, Samurai],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Kungan = Personality(
    id=12175,
    title="Kung-an",
    force=3,
    chi=3,
    personal_honor=1,
    gold_cost=5,
    honor_requirement=None,
    clan=[Unaligned],
    keywords=[Shugenja, Void],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Moto_Daigoro = Personality(
    id=12176,
    title="Moto Daigoro",
    force=4,
    chi=4,
    personal_honor=0,
    gold_cost=8,
    honor_requirement=None,
    clan=[Unaligned, ShadowlandsFaction],
    keywords=[Cavalry, Nonhuman, Samurai, Shadowlands, Undead],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Otomo_Terumoto = Personality(
    id=12177,
    title="Otomo Terumoto",
    force=0,
    chi=2,
    personal_honor=2,
    gold_cost=3,
    honor_requirement=None,
    clan=[Unaligned],
    keywords=[Courtier, Samurai, SoulOf("Otomo Taneji")],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Tonbo_Jairyu = Personality(
    id=12178,
    title="Tonbo Jairyu",
    force=3,
    chi=3,
    personal_honor=1,
    gold_cost=5,
    honor_requirement=0,
    clan=[Unaligned],
    keywords=[Naval, DragonflyClan, Shugenja, Water],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Void_Dragon_Experienced_3 = Personality(
    id=12179,
    title="Void Dragon",
    force=7,
    chi=5,
    personal_honor=4,
    gold_cost=15,
    honor_requirement=15,
    clan=[Unaligned],
    keywords=[Cavalry, Experienced("3"), Unique, Dragon, Nonhuman, Shugenja, Void],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
Water_Dragon_Experienced_3 = Personality(
    id=12180,
    title="Water Dragon",
    force=7,
    chi=5,
    personal_honor=4,
    gold_cost=15,
    honor_requirement=15,
    clan=[Unaligned],
    keywords=[Cavalry, Experienced("3"), Unique, Dragon, Nonhuman, Shugenja, Water],
    traits=[],
    abilities=[],
    legality=[TwentyFestivalsEdition, OnyxEdition, ModernEdition],
)
